### ISSUE TITLE
Installer does not properly quote strings in YAML files

### ISSUE THREAD

**Issue by brianredbeard** [openshift/installer#1012]
# Version

```console
$ openshift-install version
0.9.1
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

When rendering the various YAML files, the installer fails to quote the values which are strings.  As such this leads to ambiguity in parsing of the files.

As an example, when performing an install with a random hexadecimal cluster name beginning with an integer the installer fails to quote the string.  e.g.:

```
clusters:
- cluster:
    server: https://716064e0-api.os4.rvu.io:6443
  name: 716064e0
contexts:
- context:
    cluster: 716064e0
    user: admin
  name: admin
current-context: admin
preferences: {}
```

As a result, Kubernetes (for example) will fail to read the file with the following error:

```console
[bharrington@leviathan OPENSHIFT.RwRC]$ oc --namespace=openshift-ingress-operator get pods 
error: Error loading config file "/home/bharrington/Downloads/OPENSHIFT.RwRC/auth/kubeconfig": [pos 1602]: json: expect char '"' but got char '7'
```

# How to reproduce it (as minimally and precisely as possible)?

1. Create a cluster

For bonus points:
1b. Create a cluster with a numeric cluster name.
