### ISSUE TITLE
RFE: Add an install-config.yaml file for OpenStack

### ISSUE THREAD

**Issue by e-minguez** [openshift/installer#1080]
# Version
0.10

# Platform (aws|libvirt|openstack):

OpenStack

# What happened?

Now that OpenStack has been hidden in the wizard, it would be nice to have an example inventory-config.yaml file, otherwise it is difficult to know the parameters required.

# What you expected to happen?

Have a docs/user/openstack/install-config.yaml.example file where all the variables are explained.

# How to reproduce it (as minimally and precisely as possible)?

Try to deploy OCP on OSP

# Anything else we need to know?

# References

**Comment by zhengxiaomei123** [comment]
I am trying to do experiment with installer on OSP. A install-config.yaml.example file is necessary. Any progress here for this issue? Thanks.

**Comment by vmisson** [comment]
Hello,

beause of OpenStack multi-region using openshift-install directly is failing : 
```
? Platform openstack
? Cloud shiftstack
? Region RegionOne
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"55b2c78c7bc046b1a6230f715fd9a10d", Region:"RegionOne", RegionID:"RegionOne", Interface:"public", URL:"https://openstack.local:9696"}, tokens.Endpoint{ID:"74ea0d9d75ca4108b335337bac947288", Region:"RegionTwo", RegionID:"RegionTwo", Interface:"public", URL:"https://openstack-two.local:9696"}} 
```

A install-config.yaml.example file will be really useful.

**Comment by tomassedovic** [comment]
Hey @vmisson, sorry about the long delay! We're working on adding better documentation right now as well making OpenStack a supported platform and enabling in the interactive installer.

We're down to these pull requests:

1. https://github.com/openshift/installer/pull/1959
1. https://github.com/openshift/installer/pull/2148 (in progress)
1. https://github.com/openshift/installer/pull/2036

In the meantime, this is the `install-config.yaml` file I'm using:

```yaml
apiVersion: v1
baseDomain: openshift.example.com
controlPlane:
  name: master
  replicas: 3
compute:
- name: worker
  replicas: 3
  platform:
    openstack:
      type: m1.large
metadata:
  name: tsedovic
networking:
  clusterNetworks:
  - cidr:             10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 172.24.0.0/18
platform:
  openstack:
    cloud: standalone
    externalNetwork: external
    region: regionOne
    computeFlavor: m1.xlarge
    lbFloatingIP: 10.20.30.40
pullSecret: |
  <redacted>
sshKey: |
  <redacted>
```

Some notes:

* `lbFloatingIP` must be created in the `externalNetwork` before you start the installation.
  * e.g.: `openstack floating ip create external`
* The computer running the installer must resolve `api.tsedovic.openshift.example.com` (or whatever your `baseDomain` is) to your `lbFloatingIP` before you start the installation.
  * a proper way to do this is via configuring your DNS
  * but you can get by by adding something like this to your `/etc/hosts`:
    * `10.20.30.40 api.tsedovic.openshift.example.com`
* The `cloud` value is an entry in your `clouds.yaml` file
* The `region` name must match the region entry in your `clouds.yaml` (and it's case-sensitive!). My `standalone` OpenStack has `regionOne` a lot of other ones have `RegionOne` (or whatever else)
* The worker flavor (`m1.large` in my example) should have at least 8GB RAM. If you don't specify a worker flavor, the `platform.openstack.computeFlavor` value will be used
* The master flavor (`m1.xlarge` in my example) should have at least 16GB RAM
* I think the `networking.clusterNetworks` value is not necessary (there's a default that should be working fine), but I haven't tested it recently
* You need at least 2 workers currently. The default number is 3.

The DNS/Floating IP dance is annoying and I apologise for that. We need to support clouds without DNSaaS (Designate) and so our initial focus is on environments where you will need to add the necessary DNS records yourself.

This is my `~/.config/openstack/clouds.yaml` file:

```yaml
clouds:
  standalone:
    auth:
      auth_url: http://1.2.3.4:5000/v3
      project_name: openshift
      username: openshift
      password: <redacted>
      domain_name: default
    region_name: regionOne
    identity_api_version: 3
```

/cc @iamemilio could you please look at this and see if there's anything that can be added to your docs PR? Be nice if we could add an sample known-to-work install-config there even though we will enable the interactive installer soon.
