### ISSUE TITLE
ControlPlane master pool ignores configured zones

### ISSUE THREAD

**Issue by abutcher** [openshift/installer#1290]
# Version

```console
$ openshift-install version
./bin/openshift-install v0.9.0-master-358-g7fec739ee1ffbeda02789fece6a4feb0484fc69c
```

# Platform:

AWS

# What happened?

Using the following within install-config, which configures zones for masters and workers as us-east-1d, us-east-1e, and us-east-1f results in master instances being created in the first X=replicas availability zones in a region (us-east-1a, us-east-1b, us-east-1c) regardless of which zones are configured.

```yaml
compute:
- name: worker
  platform:
    aws:
      zones:
      - us-east-1d
      - us-east-1e
      - us-east-1f
  replicas: 3
controlPlane:
  name: master
  platform:
    aws:
      zones:
      - us-east-1d
      - us-east-1e
      - us-east-1f
  replicas: 3
```

Workers on the other hand will be created in the configured zones.

# What you expected to happen?

Configured zones are used for the master pool.

# Anything else we need to know?

Another question I have is if configured zones were used for masters, would it be possible or desirable to allow creating masters within a single availability zone or would there be some sort of protection/error from the installer in order to ensure that masters have some high availability being spread across availability zones.

# References
