### ISSUE TITLE
Additional Compute Machine Pools Rejected By Installer

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#1367]
# Version

```console
$ openshift-install version
./bin/openshift-install v0.13.1
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

In https://github.com/openshift/installer/pull/1231 support was added for additional compute machine sets, but validation is still blocking this.

FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: compute[1].name: Unsupported value: "infra": supported values: "worker" 

# How to reproduce it (as minimally and precisely as possible)?

Install Config containing:

```
compute:                                                                                                                                                                                          
- name: worker                                                                                                                                                                                    
  platform:
    aws:                                                                                                                                                                                          
      rootVolume:
        iops: 100
        size: 22
        type: gp2
      type: m4.large
  replicas: 3
- name: infra
  platform:
    aws:
      rootVolume:
        iops: 100
        size: 22
        type: gp2
      type: m4.large
  replicas: 2
```
