### ISSUE TITLE
Multiple NAT Gateways created for single AZ cluster

### ISSUE THREAD

**Issue by jewzaam** [openshift/installer#1411]
# Version

```console
$ docker run -it --rm quay.io/twiest/installer:20190227 version
/bin/openshift-install v0.13.0
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

Provisioned a cluster with 1 master and 1 worker via Hive in us-west-2.  Specified a single zone on each: us-west-2a.

The cluster is provisioned and works. But I see NAT gateway in zones us-west-2{a,b,c,d}.

Enter text here.
# What you expected to happen?

Single NAT gateway in us-west-2a.

# How to reproduce it (as minimally and precisely as possible)?

I have not boiled this down to using the installer directly, but talked to @dgoodwin and he said it's something installer should look at.

Steps for hive:

1. create pull secret
2. create aws secret
3. create ssh secret
4. create ClusterDeployment

Relevant bits of ClusterDeployment:
```yaml
apiVersion: hive.openshift.io/v1alpha1
kind: ClusterDeployment
spec:
  compute:
  - name: worker
    platform:
      aws:
        rootVolume:
          iops: 100
          size: 32
          type: gp2
        type: m5.xlarge
        zones:
        - us-west-2a
    replicas: 1
  controlPlane:
    name: master
    platform:
      aws:
        rootVolume:
          iops: 100
          size: 32
          type: gp2
        type: m5.xlarge
        zones:
        - us-west-2a
    replicas: 1
```

# Anything else we need to know?

Behavior observed results in more NAT Gateways than zones used by infrastructure.  Expect there may be some reliability gains but loss of the single zone means a loss of the cluster.  I see the additional NAT Gateways as unnecessary expense for customers, almost $100 / month in this scenario.
