### ISSUE TITLE
RFE: openshift-install allow whitelisted registries

### ISSUE THREAD

**Issue by ravigude** [openshift/installer#1426]
```console
$  openshift-install version
./openshift-install v0.14.0
```

# Platform (aws|libvirt|openstack):

aws

In Corp environment , only couple image registries are whitelisted. I am sure this is common across other orgs. We need a way to specify whitelisted registries like in `/etc/origin/master/master-config.yaml`  at cluster creation

```
imagePolicyConfig:
  allowedRegistriesForImport:
  -
    domainName: registry.redhat.io
    insecure: true
```
