### ISSUE TITLE
Error "unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1:" when trying to create a new-app

### ISSUE THREAD

**Issue by mwoodson** [openshift/installer#153]
### Tectonic version ([release](https://github.com/openshift/installer/releases) or commit hash):
```
ffca3e23530bad0efb2ebaef8d5d9cb147b6374f
```

### Terraform version (`terraform version`):

```
Terraform v0.11.7
```
### Platform (aws|azure|openstack|metal|vmware):

```
aws
```

### What happened?

```
I created the AWS cluster using the readme.  It spun up a cluster.  I am trying to deploy this

https://github.com/sclorg/nodejs-ex

I then issued the following commands (with the appropriate kubeconfig):
oc new-project nodejs-echo  --display-name="nodejs" --description="Sample Node.js app"
oc project nodejs-echo

oc --config=kubeconfig create -f https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json

# This is where the trouble starts
oc --config=kubeconfig new-app https://github.com/sclorg/nodejs-ex -l name=myapp
--> Found image 1bb994c (39 hours old) in image stream "nodejs-echo/nodejs" under tag "10" for "nodejs"

    Node.js 10.9.0 
    -------------- 
    Node.js  available as docker container is a base platform for building and running various Node.js  applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.

    Tags: builder, nodejs, nodejs-10.9.0

    * The source repository appears to match: nodejs
    * A source build using source code from https://github.com/sclorg/nodejs-ex will be created
      * The resulting image will be pushed to image stream tag "nodejs-ex:latest"
      * Use 'start-build' to trigger a new build
    * This image will be deployed in deployment config "nodejs-ex"
    * Port 8080/tcp will be load balanced by service "nodejs-ex"
      * Other containers can access this service through the hostname "nodejs-ex"

error: Unable to to get list of available resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

```

### What you expected to happen?

```
I would expect the app to build to completion
```

### How to reproduce it (as minimally and precisely as possible)?

```
See above
```

### Anything else we need to know?
```
Here is the config I used to create the cluster

admin:
  email: openshift-cr@redhat.com
  password: xxxxx
  sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7GW7qcnemBaZMw+8UNfgqwTvv6pPKftQtBZowfXfPRq5TWivRMnW/5SlW5eiLWrYsgAfnC/bREuBnE6lRmxeH2rKXb/WW1aLqNAe5XvC2xYaH9kXpQoaQWD6hbWL0mHfHowj1sWOrN25YETLbVJ3Wh4rLugIPIDKteB91HoZlv5N5Tao4yZO7YxMMScqDEo//Asdua+jCzCEuNZmSyqYZjuO8Ub20FP76Di2avR4qtrxgakIi2SxpwtCZLJndJCYI7COTSuF1WCv+uMjafLTaCeEtLw5GnoLCpb7nPqocgBFWKcJ58RkxX76JPOpdGLCLasvxS7/6pmDMyB/eO3vH
aws:
  region: us-west-1
baseDomain: crtest.openshift.com
ca: null
containerLinux:
  version: latest
etcd:
  nodePools:
  - etcd
iscsi: null
licensePath: xxxxx
master:
  nodePools:
  - master
name: rhcos-cr
networking:
  podCIDR: 10.2.0.0/16
  serviceCIDR: 10.3.0.0/16
nodePools:
- count: 3
  name: etcd
- count: 1
  name: master
- count: 3
  name: worker
platform: aws
pullSecretPath: xxxxx
worker:
  nodePools:
  - worker


```

### References

```
N/A```

**Comment by mwoodson** [comment]
@abhinavdahiya

**Comment by abhinavdahiya** [comment]
```yaml
networking:
  podCIDR: 10.2.0.0/16
  serviceCIDR: 10.3.0.0/16
```
This section by default chose `canal` as network provider.There are some unresolved problems with network policy which prevented apiserver from talking to metrics server. Please use `flannel`.

```yaml
networking:
  podCIDR: 10.2.0.0/16
  serviceCIDR: 10.3.0.0/16
  type: flannel
```

NOTE: https://github.com/openshift/installer/pull/151 moved default to `flannel`
