### ISSUE TITLE
AddressLimitExceeded

### ISSUE THREAD

**Issue by ofrzeta** [openshift/installer#1609]
# Version

```console
$ openshift-install version
./bin/openshift-install unreleased-master-777-g003f14523a7ccc319150a6a8fa3f8fe499794787

```

# Platform: 

aws

# What happened?

Installation failed with 

```
ERROR 	* module.vpc.aws_eip.nat_eip[4]: 1 error occurred: 
ERROR 	* aws_eip.nat_eip.4: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached. 
```

# What you expected to happen?

Installation should succeed

# Anything else we need to know?

I followed the instructions on AWS limits in the installer docs and restricted the nodes to one AZ (see below) but the installation still failed. I checked the EIP limits and it's the default 5.

```
apiVersion: v1beta4
baseDomain: cloud.zetalab.de
compute:
- name: worker
  platform: {}
  replicas: 2
  zones: 
    - us-east-1a
controlPlane:
  name: master
  platform: {}
  replicas: 1
  zones: 
    - us-east-1a
metadata:
  creationTimestamp: null
  name: ocp4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
```

**Comment by abhinavdahiya** [comment]
> ```
> apiVersion: v1beta4
> baseDomain: cloud.zetalab.de
> compute:
> - name: worker
>   platform: {}
>   replicas: 2
>   zones: 
>     - us-east-1a
> controlPlane:
>   name: master
>   platform: {}
>   replicas: 1
>   zones: 
>     - us-east-1a
> metadata:
>   creationTimestamp: null
>   name: ocp4
> networking:
>   clusterNetwork:
>   - cidr: 10.128.0.0/14
>     hostPrefix: 23
>   machineCIDR: 10.0.0.0/16
>   networkType: OpenShiftSDN
>   serviceNetwork:
>   - 172.30.0.0/16
> platform:
>   aws:
>     region: us-east-1
> ```

you have an invalid install-config:

zones information goes in the `platform` section of the machinepool https://godoc.org/github.com/openshift/installer/pkg/types#MachinePool

```yaml
apiVersion: v1beta4
baseDomain: devcluster.openshift.com
controlPlane:
  name: master
  hyperthreading: Disabled
  replicas: 3
  platform:
    aws:
      zones:
      - us-east-1a
compute:
- name: worker
  replicas: 3
  platform:
    aws:
      zones:
      - us-east-1a
metadata:
  name: adahiya-1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
```

/close
