### ISSUE TITLE
Exit return code to a timeout condition is '0' which should be non-zero

### ISSUE THREAD

**Issue by praveenkumar** [openshift/installer#1636]
# Version

```console
$ openshift-install  version
openshift-install unreleased-master-819-g8c607f66662f8e35570960484612d0589c26b654
built from commit 8c607f66662f8e35570960484612d0589c26b654
release image registry.svc.ci.openshift.org/origin/release:v4.1
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?
After getting the timeout for `waiting for the cluster initialize` the exit return code from the installer is `0`

# What you expected to happen?
The exit return code from installer should be non zero if it doesn't success.

# How to reproduce it (as minimally and precisely as possible)?

```console
[prkumar@prkumar-nested-virttest ~]$ openshift-install create cluster
[...]
urce, check extension API servers"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: downloading update"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 0% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 8% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 21% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 29% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 33% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 34% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 90% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 90% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 90% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: downloading update"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 11% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 24% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 29% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 95% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 96% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-0.okd-2019-04-17-024406: 96% complete"
level=fatal msg="failed to initialize the cluster: Working towards 4.1.0-0.okd-2019-04-17-024406: 96% complete: timed out waiting for the condition"

[prkumar@prkumar-nested-virttest ~]$ echo $?
0
```

# Anything else we need to know?

[openshift_install.log](https://github.com/openshift/installer/files/3087931/openshift_install.log)

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
using this install-config to fail during install-ready.
```yaml
apiVersion: v1beta4
baseDomain: tt.testing
compute:
- name: worker
  hyperthreading: Disabled
  platform: {}
  replicas: 0
controlPlane:
  name: master
  hyperthreading: Disabled
  platform: {}
  replicas: 1
metadata:
  name: adahiya-0
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
```
```console
[3:00:12] ➜  installer git:(master) ✗  ./bin/openshift-install version
./bin/openshift-install unreleased-master-823-g06c987df7c7d0384f02b00fa4d26a2253e7a8c9f
built from commit 06c987df7c7d0384f02b00fa4d26a2253e7a8c9f
release image registry.svc.ci.openshift.org/origin/release:v4.1

[3:00:47] ➜  installer git:(master) ✗ ./bin/openshift-install --dir dev create cluster
WARNING There are no compute nodes specified. The cluster will not fully initialize without compute nodes.
WARNING Found override for OS Image. Please be warned, this is not advised
INFO Consuming "Install Config" from target directory
INFO Creating infrastructure resources...
INFO Waiting up to 30m0s for the Kubernetes API at https://api.adahiya-0.tt.testing:6443...
INFO API v1.13.4+938b976 up
INFO Waiting up to 30m0s for the bootstrap-complete event...
INFO Destroying the bootstrap resources...
INFO Waiting up to 30m0s for the cluster at https://api.adahiya-0.tt.testing:6443 to initialize...
FATAL failed to initialize the cluster: Working towards 4.1.0-0.okd-2019-04-17-205308: 93% complete: timed out waiting for the condition
[3:00:47] ➜  installer git:(master) ✗ echo $?
1
[3:03:32] ➜  installer git:(master) ✗
```

I cannot reproduce this error.

**Comment by praveenkumar** [comment]
@abhinavdahiya Let me test with single node scenario also but with default config for libvirt I am able to reproduce it multiple time. The install config I am using is below one.

```yaml
apiVersion: v1beta3
baseDomain: tt.testing
compute:
- name: worker
  replicas: 1
controlPlane:
  name: master
  replicas: 1
metadata:
  name: test1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  libvirt:
    URI: qemu+tcp://libvirt.default/system
    network:
      if: tt0
```
