### ISSUE TITLE
non-human readable fields in marshalled InstallConfig

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/installer#215]
The current `pkg/types.InstallConfig`'s networking section marshals to
```yaml
    networking:
      podCIDR:
        IP: 10.2.0.0
        Mask: //8AAA==
      serviceCIDR:
        IP: 10.3.0.0
        Mask: //8AAA==
      type: canal
```
This is not human readable or editable, which the `InstallConfig` needs to be.
