### ISSUE TITLE
Dynamically provisioned storage doesn't work on OpenStack

### ISSUE THREAD

**Issue by ppitonak** [openshift/installer#2263]
# Version

```console
$ openshift-install version
openshift-install v4.2.0-201908221819-dirty
built from commit 605fa00f755385527eb4c07eb23256f895c9c324
release image registry.svc.ci.openshift.org/ocp/release@sha256:6628d1329757d884c88cb2bc9569ec53eb6b56e0681d55fe2d694b0e1e35d162
```

# Platform:
OpenStack 13

# What happened?

Dynamically provisioned storage does not work. PVC stays in `unbound` state forever.

# What you expected to happen?

In freshly installed cluster, when I create a PVC of storage class `standard`, and use it in a pod, I expect a volume to be provisioned in OpenStack.

# How to reproduce it (as minimally and precisely as possible)?

1. install a new cluster
2. open console and navigate to Dashboards -> Persistent Storage

Message `Ceph is not available` is present in Health section

```console
$ oc login ...
$ oc apply -f pvc.yaml
$ oc apply -f pod.yaml
$ oc get pvc
NAME           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cinder-claim   Pending
$ oc get pods
NAME      READY   STATUS    RESTARTS   AGE
example   0/1     Pending   0          14m
```
where pvc.yaml contains

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cinder-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
```

pod.yaml

```
kind: Pod
metadata:
  name: example
  labels:
    app: hello-openshift
spec:
  volumes:
    - name: cinder-claim
      persistentVolumeClaim:
        claimName: cinder-claim
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: cinder-claim
```

# Anything else we need to know?

https://bugzilla.redhat.com/show_bug.cgi?id=1747474

Couple of events:

```
17m         Normal    WaitForFirstConsumer                  persistentvolumeclaim/cinder-claim   waiting for first consumer to be created before binding
7m17s       Warning   FailedScheduling                      pod/example                          timed out waiting for the condition
6m7s        Warning   FailedScheduling                      pod/example                          AssumePod failed: pod 08017cb1-c5ba-11e9-adb1-fa163e4a8d8b is in the cache, so can't be assumed
```
