### ISSUE TITLE
ipv6 CIDR to be used for kubernetes Pods and Services networks

### ISSUE THREAD

**Issue by kmabda** [openshift/installer#2318]
# Version

```console
$ openshift-install version
openshift-install v4.1.9-201907311355-dirty
built from commit d67b11e14c2c7f4a997100784a54fdba35e5ee74
release image quay.io/openshift-release-dev/ocp-release@sha256:27fd24c705d1107cc73cb7dda8257fe97900e130b68afc314d0ef0e31bcf9b8e
```

# Platform:

none (UPI)
# What happened?
the openshift installer refuse to generate the ignition files with a ipv6 cird for the clusterNetworks and serviceNetwork

FATAL failed to fetch Kubeconfig Admin Client: failed to load asset "Install Config": invalid "install-config.yaml" file: [networking.serviceNetwork[0]: Invalid value: "fd03:aabb::/64": must use IPv4, networking.clusterNetwork[0].cidr: Invalid value: "fd02:aabb::/64": must use IPv4]

# What you expected to happen?

ignitions files for the bootstrap, master and worker nodes generated

# How to reproduce it (as minimally and precisely as possible)?
The install-config.yaml used looks like this:
```
apiVersion: v1
baseDomain: ocp.lab
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 1
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cl1
networking:
  clusterNetworks:
  - cidr: fd02:aabb::/64
    hostPrefix: 96
  networkType: OpenShiftSDN
  serviceNetwork:
  - fd03:aabb::/64
platform:
  none: {}
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"xxx"}}}'
```

```console
$ mkdir assets
$ cp install-config-ipv6.yaml assets/install-config.yaml
$ openshift-install --dir=./assets create ignition-configs
```

# Anything else we need to know?

Part of the validation of the install-config.yaml file content provided to openshift installer there is an explicit check for IPv4 only subnets [1]

Is this use case supported?

Noticed also that all the registries used to pull images needed to install OpenShift have no AAAA records [2], [3]: cloud.openshift.com,  quay.io, registry.connect.redhat.com, registry.redhat.io

Which means the master, worker and the bootstrap nodes must have right now ipv4 connectivity over the internet.

# References
[1] https://github.com/openshift/installer/blob/master/pkg/validate/validate.go#L110
[2] /var/lib/kubelet/config.json from a master/worker node
[3] /etc/containers/registries.con from a bootstrap node

**Comment by dcbw** [comment]
v6 will require Kubernetes v1.16 and will be subject to the limitations described in https://github.com/kubernetes/enhancements/pull/808

**Comment by morvencao** [comment]
Same issue!

@dcbw OCP 4.2 introduced OVN as TP feature, which should support IPV6, isn't it?

So I thought the following `install-config.yaml` should work for IPv6:
```
apiVersion: v1
baseDomain: myk8s.io
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: mycluster
networking:
  clusterNetwork:
  - cidr: fd02:aabb::/64
    hostPrefix: 96
  machineCIDR: fd03:aabb::/64
  networkType: OVNKubernetes
  serviceNetwork:
  - fd04:aabb::/64
platform:
...
```
