### ISSUE TITLE
Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded

### ISSUE THREAD

**Issue by xjtustt** [openshift/installer#2516]
# Version

```console
$ openshift-install version
openshift-install4.2 v4.2.0
built from commit b5aebb52f4b363e942234cd7d7f1c145d044c2ef
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:75f065cf0590077ffba27ac61e104420660b8d2a344e09a11edd3cde50d14b01
```

# Platform:
gcp

# What happened?
Encountered the error that `Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded`

# What you expected to happen?
OCP cluster can be provisioned correctly on gcp platform.

# How to reproduce it (as minimally and precisely as possible)?
1. download openshift-install v4.2 from https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/4.2.0-0.nightly-2019-10-07-203748/
2. generate a config yaml like what I attached through `openshift-install create install-config`
3. install cluster through `openshift-install create cluster`

```console
$ openshift-install create install-config
$ openshift-install create cluster
DEBUG Apply complete! Resources: 73 added, 0 changed, 0 destroyed.
DEBUG OpenShift Installer v4.2.0
DEBUG Built from commit b5aebb52f4b363e942234cd7d7f1c145d044c2ef
INFO Waiting up to 30m0s for the Kubernetes API at https://api.marcotest.mcmlab.google.com:6443...
DEBUG Still waiting for the Kubernetes API: Get https://api.marcotest.mcmlab.google.com:6443/version?timeout=32s: dial tcp: lookup api.marcotest.mcmlab.google.com on 9.0.149.140:53: no such host
DEBUG Still waiting for the Kubernetes API: Get https://api.marcotest.mcmlab.google.com:6443/version?timeout=32s: dial tcp: lookup api.marcotest.mcmlab.google.com on 9.0.149.140:53: no such host
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: EOF
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
```

# Anything else we need to know?

# References

**Comment by xjtustt** [comment]
The install log is here:
[openshift_install.log](https://github.com/openshift/installer/files/3733479/openshift_install.log)

And my install-config.yaml is here:
```yaml
apiVersion: v1
baseDomain: mcmlab.google.com
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: marcotest
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: oceanic-guard-191815
    region: us-east1
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3poaXdlaWNuaWJtY29tMWxsaHJrYXNxbnhrbXVxbXZsd2ZybHNxdGFrOlo4V0ZYTEpYOUkxRE0zNEdTTVpSNThVTENNWVZCQ0tHS09HTzhVRFE2UUlTMldOMlZNOUgyWUNQTEVXVjVWWUU=","email":"zhiwei@cn.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3poaXdlaWNuaWJtY29tMWxsaHJrYXNxbnhrbXVxbXZsd2ZybHNxdGFrOlo4V0ZYTEpYOUkxRE0zNEdTTVpSNThVTENNWVZCQ0tHS09HTzhVRFE2UUlTMldOMlZNOUgyWUNQTEVXVjVWWUU=","email":"zhiwei@cn.ibm.com"},"registry.connect.redhat.com":{"auth":"NTI1ODcwOTN8dWhjLTFMTEhya2FzcU5Ya21VUW1WTFdmckxzUVRBSzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJabU5tTXpRNVptUTVPRFEwTlRVNVltUXpNekEwWlRZNVpqYzJOVFpoTVNKOS50TEhnWDFSaXpNdGpmUUlyRGJ2TkkxbUdyR1BiWFI1TmR2TVEyX1oyd2FYTkc2eFJ1b25xSC11ZkZVMEx4Q2hLYWRSRV80bXNDZDNQSHlrQUV3UkdxVHc1aGg0WU1RdXNrdXdfUy1uUlU1WXhYVU9WdFpxd2F5Ykhkc19seVNBN29mMXY1Y2wzRklucExCd0dXV19kblRaN01Fb3dWcGZDUlRqRFF5cDExOWlqWWZkTDByZzNmOUFvMm9ZaWxRR1ZjSzRNVHBqWXR2ZFVnSF9GdWRoRTBVb05Ca2tNOER1aW90UDIwT2YzRkRqd0liN0xfaG5GeTVTSEdYWWhZUWhQTXNNdGJMeTJ1SXVTdGRKUm5UMEdPOVQ4em8yZm9zaExsYm5TZUViblBjb2gwR3gxQmtEcERyVkhTSEk5SVplQTVZRVdIaWpaVFhnb3BCSDljdGZiMHJYeE9saVRhLUNfa2U4RDFrODExUXhBcjIxd1doTnJxQ0wwai1Mc01JcnB5Y0ROLUZXaEkwY2hqT3MybGJuNV9VYlVxS09JcFNWNXNOZVYyU2JyQW9HWFZmVENuSGczQWRjTklZV3hLWGxncGhhVmloTHVpazF5WDIzU3RydlJIZmhMRTFzTUs0OUFiWmNsbEQ2bHE1MXQ1VjYtaHZkbGZwcllZbDZMeWF3UDV0ZXQ2TlBsUXhyYmVWeTJGMXFUcVVFd1dqM19ETmQ0b0dmTTdrVjRZNE5SWFBfYm1IdmtkaUF0ZkZVWS1IN1F1al96dHhCUWxEOHF1UERERzBGWXJFV1VMQ3o4aUp6dmxnZlBrTS1sTzJReTJBUXZHeHJ6VGxDbllSaFBqay1hMENmWHNOejFOYnJzT1kzTk80OHcyTDU5SXJndUt5R3pQZUhxTWFfNDBUQQ==","email":"zhiwei@cn.ibm.com"},"registry.redhat.io":{"auth":"NTI1ODcwOTN8dWhjLTFMTEhya2FzcU5Ya21VUW1WTFdmckxzUVRBSzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJabU5tTXpRNVptUTVPRFEwTlRVNVltUXpNekEwWlRZNVpqYzJOVFpoTVNKOS50TEhnWDFSaXpNdGpmUUlyRGJ2TkkxbUdyR1BiWFI1TmR2TVEyX1oyd2FYTkc2eFJ1b25xSC11ZkZVMEx4Q2hLYWRSRV80bXNDZDNQSHlrQUV3UkdxVHc1aGg0WU1RdXNrdXdfUy1uUlU1WXhYVU9WdFpxd2F5Ykhkc19seVNBN29mMXY1Y2wzRklucExCd0dXV19kblRaN01Fb3dWcGZDUlRqRFF5cDExOWlqWWZkTDByZzNmOUFvMm9ZaWxRR1ZjSzRNVHBqWXR2ZFVnSF9GdWRoRTBVb05Ca2tNOER1aW90UDIwT2YzRkRqd0liN0xfaG5GeTVTSEdYWWhZUWhQTXNNdGJMeTJ1SXVTdGRKUm5UMEdPOVQ4em8yZm9zaExsYm5TZUViblBjb2gwR3gxQmtEcERyVkhTSEk5SVplQTVZRVdIaWpaVFhnb3BCSDljdGZiMHJYeE9saVRhLUNfa2U4RDFrODExUXhBcjIxd1doTnJxQ0wwai1Mc01JcnB5Y0ROLUZXaEkwY2hqT3MybGJuNV9VYlVxS09JcFNWNXNOZVYyU2JyQW9HWFZmVENuSGczQWRjTklZV3hLWGxncGhhVmloTHVpazF5WDIzU3RydlJIZmhMRTFzTUs0OUFiWmNsbEQ2bHE1MXQ1VjYtaHZkbGZwcllZbDZMeWF3UDV0ZXQ2TlBsUXhyYmVWeTJGMXFUcVVFd1dqM19ETmQ0b0dmTTdrVjRZNE5SWFBfYm1IdmtkaUF0ZkZVWS1IN1F1al96dHhCUWxEOHF1UERERzBGWXJFV1VMQ3o4aUp6dmxnZlBrTS1sTzJReTJBUXZHeHJ6VGxDbllSaFBqay1hMENmWHNOejFOYnJzT1kzTk80OHcyTDU5SXJndUt5R3pQZUhxTWFfNDBUQQ==","email":"zhiwei@cn.ibm.com"}}}'
```

@gyliu513 FYI.

**Comment by xjtustt** [comment]
The install log is here:
[openshift_install.log](https://github.com/openshift/installer/files/3733519/openshift_install.log)

And my install-config.yaml is here:
```yaml
apiVersion: v1
baseDomain: <my-base-domain>
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: marcotest
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: <my-project>
    region: us-east1
pullSecret: '<my-pull-secret>'
```
