### ISSUE TITLE
[Question/Feature] Define custom libvirt storage pool location in install-config.yml

### ISSUE THREAD

**Issue by oswee** [openshift/installer#2535]
Is there an documentation or option to define custom storage pool location for libvirt installation?
Would like to have something like:
```yaml
...
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
    pool:
      path: /my/custom/pool/path
      name: openshift
...
```
Currently installer uses default libvirt pool location in `/var/lib/libvirt/images` which in my case is specific drive with some constraints and i can't use that.
I have `default` pool defined as well (in custom location), but seems openshift-installer ignores that.
So second option (less preferable) would be to check, is `default` pool defined and if so, then to place ocp volumes there.

How can i force openshift-installer to use custom pool location? Should i modify Go code before compiling installer?
