### ISSUE TITLE
baremetal IPI profile in install-config

### ISSUE THREAD

**Issue by karmab** [openshift/installer#2705]
# Version

```console
$ openshift-install version
./openshift-baremetal-install unreleased-master-2170-ga702fd4beb593932067fe1b31f2d911feaa6d93e
built from commit a702fd4beb593932067fe1b31f2d911feaa6d93e
release image registry.svc.ci.openshift.org/origin/release:4.3
```

# Platform:

baremetal

# What happened?
when trying to deploy workers along with the masters, i got the masters provisioned and the baremetal hosts objects associated to the workers created but not provisioned
removing hardware: profile from their spec triggered the install.
This seems to be caused by defaulting to "default" instead of the "unknown" profile

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

A deployment of my workers at install time

# How to reproduce it (as minimally and precisely as possible)?
deploy with at least one worker

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by stbenjam** [comment]
Thanks!

I think the issue is setting the hardware profile to `default`, where the BMO uses the name `unknown`. The way I handled this wasn't super well thought through in the installer: https://github.com/openshift/installer/blob/master/pkg/tfvars/baremetal/baremetal.go#L43-L45

I'm not sure why the workers are ending up with the `default` profile, though. Need to track that down.

**Comment by dhellmann** [comment]
@karmab Could you provide the information about the hardware in the install-config file you used, without the passwords to the BMC? I'm curious to see exactly how the data was passed to the installer.

**Comment by karmab** [comment]
```
apiVersion: v1
baseDomain: karmalabs.com
networking:
  machineCIDR: 192.168.120.0/24
metadata:
  name: doug
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 1
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.120.100
    dnsVIP: 192.168.120.101
    ingressVIP: 192.168.120.102
    provisioningBridge: provisioning
    externalBridge: baremetal
    libvirtURI: qemu+ssh://root@192.168.120.1/system
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://192.168.121.1
          username: root
          password: jmayer
        bootMACAddress: 98:03:9b:61:80:48
        hardwareProfile: default
      - name: openshift-worker-1
        role: worker
        bmc:
          address: ipmi://192.168.121.2
          username: root
          password: eclapton
        hardwareProfile: default
        bootMACAddress: 98:03:9b:61:ae:18
      - name: openshift-worker-2
        role: worker
        bmc:
          address: ipmi://192.168.121.3
          username: root
          password: jhendrix
        bootMACAddress: 98:03:9b:61:ba:d0
        hardwareProfile: default
pullSecret: |
  XXX
sshKey: |
  XXX
```
