### ISSUE TITLE
need to specify provisioning interface by host instead of globally

### ISSUE THREAD

**Issue by dhellmann** [openshift/installer#2762]
# Version 4.3/4.4

# Platform:

baremetal

# What happened?

The bare metal configuration asks for 1 provisioning network interface so that the machine-api-operator can configure the metal3 services to listen on that network. The interface is specified globally, under the simplifying assumption that the hardware in a given cluster would be uniform. 

# What you expected to happen?

We may no longer be able to make that assumption, and so we need to find a way to specify a provisioning interface for each host.

# How to reproduce it (as minimally and precisely as possible)?

Build a bare metal cluster with a control plane made up of different types of servers so that the network interfaces are assigned different names by the OS.

# Anything else we need to know?

# References

**Comment by dhellmann** [comment]
label platform/baremetal

**Comment by dhellmann** [comment]
In the conversation where this issue came up, we considered whether we could use the MAC address we already have for a host to determine the interface. We don't think we can, because in some environments the provisioning net might be on a bond or VLAN or other network that doesn't use the same MAC that a host would use to PXE boot.

**Comment by hardys** [comment]
It would be good to ensure we really do expect to support heterogeneous nodes for the controlplane - it seems more likely that in most cases you'd have three identical machines to ensure consistent behavior in an HA failover scenario?

For workers, the situation is certainly different, but my assumption so far is that we'd use multiple machinesets/machineconfig to handle groups of servers there, and that we don't expect to run the metal3 provisioning components on the workers.

Note there is ongoing upstream discussion on how to do this sort of per-host personalization ref https://github.com/metal3-io/baremetal-operator/pull/348 - that might provide the long-term solution, but IIUC would be dependent on rebasing on the v1alpha2 cluster-api where the machinedeployment is decoupled?  

Also as mentioned on that PR I don't think ignition yet has any support for network_data, so we'd have to figure out how to consume it (could just be a custom script run by ignition initially I suppose).

**Comment by atyronesmith** [comment]
IMO I think it would be reasonable at a minimum to expect that the masters and the workers would have different network interface configurations (especially in the far-edge case).  In addition, strictly data-plane workers (i.e. realt-ime) network interfaces might be different than general-purpose workers giving 3 different configurations.  

What we did for our UPI work was to allow a default configuration for workers and masters separately.  i.e.  In our site-config.yaml.

```
apiVersion: kni.akraino.org/v1alpha1
kind: SiteConfig
metadata:
  name: notImportantHere
config:
  releaseImageOverride: registry.svc.ci.openshift.org/origin/release:4.2
provisioningInfrastructure:
  hosts:
    **# interface to use for provisioning on the masters
    masterBootInterface: eno2
    # interface to use for provisioning on the workers
    workerBootInterface: eno2
    # interface to use for baremetal on the masters
    masterSdnInterface: ens1f0
    # interface to use for baremetal on the workers
    workerSdnInterface: ens1f0**

  network:
    # The provisioning network's CIDR
    provisioningIpCidr: 172.22.0.0/24
    # PXE boot server IP
    # DHCP range start (usually provHost/interfaces/provisioningIpAddress + 1)
    provisioningDHCPStart: 172.22.0.11
    provisioningDHCPEnd: 172.22.0.51
    ....
```

What we also found that in environments with multiple interfaces beyond the provisioning and baremetal nics, that DHCP servers on the additional interfaces cause issues with booting RHCOS.  As RHCOS brings up all interfaces by default, interfaces could, non-deterministically, get default routes which would interrupt the boot process.  We ended up disabling all auto-configure in NetworkManager in the initial ignition files and providing specify ifcfg-<intr> files specifically for the provisioning and baremetal interfaces.  Additional interfaces were configured through the MCO.  

These scenarios might not be directly applicable in this case, but FYI....
