### ISSUE TITLE
Existing Baremetal Provisioning CR ignored

### ISSUE THREAD

**Issue by karmab** [openshift/installer#2990]
# Version

```console
$ openshift-install version
openshift-baremetal-install 4.4.0-0.nightly-2020-01-24-141203
built from commit 96d416ee36d8660c3f2cb33863587455278f4ed2
release image registry.svc.ci.openshift.org/ocp/release@sha256:e4c521b17c773c4c0b1bd5816dc5f1660df16da8a28d68dc08394b879e8c6d91
```

# Platform:

# What happened?

when deploying on baremetal, metal3 pod doesnt properly start since the switch to consuming provisioning object instead of configmap.
Despite precreating the following CR by moving it into dedicated openshift directory, it's ignored and instead a default one is used, where provisioning nic is set to ens3 (which doesnt match my env where i'm using eno1 instead)

```
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
  namespace: openshift-machine-api
spec:
  provisioningInterface: eno1
  provisioningIP: 172.22.0.3
  provisioningNetworkCIDR: 172.22.0.0/24
  provisioningDHCPExternal: False
  provisioningDHCPRange: 172.22.0.10,172.22.0.100
```

# What you expected to happen?

Install to properly finish

# How to reproduce it (as minimally and precisely as possible)?

Deploy latest openshift on baremetal, creating a custom provisioning object
