### ISSUE TITLE
after failed azure install, tries to run must-gather against a private IP

### ISSUE THREAD

**Issue by danwinship** [openshift/installer#3026]
# Version

```console
$ openshift-install version
openshift-install 4.4.0-0.ci-2020-01-30-103649
built from commit e1a6a984b73a818a48f800eecc05ebbc526fc5b9
release image registry.svc.ci.openshift.org/ocp/release@sha256:de6100fae89e871659e942bbeee5eea2f061cc3dd463d4f4ad5893a6b1883e3f
```

# Platform:
azure

# What happened?
Attempted an IPv6 install. Failed (as expected). openshift-install reported:

```
INFO Pulling debug logs from the bootstrap machine 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: dial tcp 10.0.0.8:22: connect: connection timed out 
```

# What you expected to happen?

It should have tried to ssh to the bootstrap host's *public* IP, not its private IP.

# How to reproduce it (as minimally and precisely as possible)?

Try to install an azure cluster and fail. I don't know if the failure mode is IPv6-specific or if it happens with IPv4 clusters too. (It's possible that something is assuming that the host's public IP is the Nth element of some list, but if there are both IPv4 and IPv6 IPs then N is different?)

networking portion of the install-config:

```
networking:
  clusterNetwork:
  - cidr: fd01::/48
    hostPrefix: 64
  machineNetwork:
  - cidr: 10.0.0.0/16
  - cidr: fc00::/48
  networkType: OVNKubernetes
  serviceNetwork:
  - fd02::/112
```

```console
$ OPENSHIFT_INSTALL_AZURE_EMULATE_SINGLESTACK_IPV6=true openshift-install --dir ... create cluster
```
