### ISSUE TITLE
aws example is unclear

### ISSUE THREAD

**Issue by bparees** [openshift/installer#312]
Trying to fill in the aws.yaml per the instructions, there's a lack of help to figure out what i'm supposed to do with it.

```
admin:
  email: "a@b.c"
  password: "verysecure"
  sshKey: "ssh-ed25519 AAAA..."
```

what are these values?  ssh credentials for aws?  a cluster-admin account that's going to be created? something else entirely?
