### ISSUE TITLE
Openshift install fails due to x509 ip address parse failure

### ISSUE THREAD

**Issue by stephenliang** [openshift/installer#3127]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-2546-g43bed121efd7d9b3353e7ef5bd85dae07e0cc97e
built from commit 43bed121efd7d9b3353e7ef5bd85dae07e0cc97e
release image registry.svc.ci.openshift.org/origin/release:4.3```
```

# Platform:
ovirt

# What happened?

Following the installation guide for openshift, I configured the ovirt install-config using the ovirt survey and created an ovirt-config. When I attempt to create manifests, the installer fails due to an x509 error: `failed to generate signed cert/key pair: error parsing x509 certificate request: x509: cannot parse IP address of length 0`.

# What you expected to happen?

Installer does not fail.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install --log-level debug create manifests
```

# Anything else we need to know?

The ovirt installation uses a self-signed certificate from a self-hosted install.

```
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Network Config"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Proxy Config..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Scheduler Config..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Install Config..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Install Config"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Scheduler Config..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Image Content Source Policy..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Install Config..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Install Config"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Image Content Source Policy..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Root CA..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Reusing previously-fetched Root CA"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (etcd-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Certificate (etcd-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (etcd-ca-bundle)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Certificate (etcd-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Certificate (etcd-signer)"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Certificate (etcd-ca-bundle)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (etcd-client)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Certificate (etcd-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Certificate (etcd-signer)"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Certificate (etcd-client)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (etcd-metric-ca-bundle)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Certificate (etcd-metric-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Generating Certificate (etcd-metric-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Certificate (etcd-metric-ca-bundle)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (etcd-metric-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Reusing previously-fetched Certificate (etcd-metric-signer)"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (etcd-metric-signer-client)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Certificate (etcd-metric-signer)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Certificate (etcd-metric-signer)"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Certificate (etcd-metric-signer-client)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="  Fetching Certificate (mcs)..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Root CA..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Root CA"
time="2020-02-18T08:47:40-08:00" level=debug msg="    Fetching Install Config..."
time="2020-02-18T08:47:40-08:00" level=debug msg="    Reusing previously-fetched Install Config"
time="2020-02-18T08:47:40-08:00" level=debug msg="  Generating Certificate (mcs)..."
time="2020-02-18T08:47:41-08:00" level=fatal msg="failed to fetch Common Manifests: failed to fetch dependency of \"Common Manifests\": failed to generate asset \"Certificate (mcs)\": failed to generate signed cert/key pair: error parsing x509 certificate request: x509: cannot parse IP address of length 0"
```

# References

**Comment by abhinavdahiya** [comment]
/assign @rgolangh 
@stephenliang Please don't build installer from source, rather use https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.4/

**Comment by stephenliang** [comment]
Same issue on ocp-dev-preview:

```
openshift-install v4.4.0
built from commit 43bed121efd7d9b3353e7ef5bd85dae07e0cc97e
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:3dd2b6f2ad288f220005c48e92c287bfde8eaa74735afa0a5cf469fc20eac8
```

```
DEBUG   Fetching Certificate (mcs)...
DEBUG     Fetching Root CA...
DEBUG     Reusing previously-fetched Root CA
DEBUG     Fetching Install Config...
DEBUG     Reusing previously-fetched Install Config
DEBUG   Generating Certificate (mcs)...
FATAL failed to fetch Common Manifests: failed to fetch dependency of "Common Manifests": failed to generate asset "Certificate (mcs)": failed to generate signed cert/key pair: error parsing x509 certificate request: x509: cannot parse IP address of length 0
```

**Comment by rgolangh** [comment]
The ovirt certificate is not relevant. Its the creation of the certificate for the MCS.
Can you share you `install-config.yaml` ? I suspect the api_vip address is missing there. `installConfig.Config.Ovirt.APIVIP`

**Comment by stephenliang** [comment]
It looks like api_vip is defined. I used an unused ip address for those questions in the survey.

```
apiVersion: v1
baseDomain: xxxxxxx
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: xxxxxx
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  ovirt:
    api_vip: 192.168.100.280
    dns_vip: 192.168.100.281
    ingress_vip: 192.168.100.282
    ovirt_cluster_id: cf00cd04-2f2b-11e9-9f60-00163e3a59b9
    ovirt_network_name: ovirtmgmt
    ovirt_storage_domain_id: 35c93f0c-bf21-47f9-b395-257237356f85
publish: External
pullSecret: xxxxxxx
```
