### ISSUE TITLE
openstack - destroy cluster fails with self signed cert on cloud endpoint

### ISSUE THREAD

**Issue by dlbewley** [openshift/installer#3216]
# Version

```console
$ oc version
Client Version: 4.4.0-0.nightly-2020-01-31-125528
Server Version: 4.4.0-0.nightly-2020-02-03-224632
Kubernetes Version: v1.17.1

$ openshift-install version
openshift-install v4.4.0
built from commit 1239635604dc7cee03b1cbc7894874a793417c3f
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:011c3e43b3ae34fd423ea8d65ec2e63e76e239dfe265f4927559c84ed04dd58d
```

# Platform:

- OpenStack Queens OSP 13

# What happened?

Destroying cluster fails due to lack of trust in endpoint TLS. eg. below repeats for each resource type.

```
time="2020-03-02T16:10:12-08:00" level=debug msg="OpenShift Installer v4.4.0"
time="2020-03-02T16:10:12-08:00" level=debug msg="Built from commit 1239635604dc7cee03b1cbc7894874a793417c3f"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack floating ips"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack routers"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack base image"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack ports"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack subnets"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack containers"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack networks"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack servers"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack load balancers"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack trunks"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack subnet-pools"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting OpenStack volumes"
time="2020-03-02T16:10:12-08:00" level=debug msg="Deleting openstack security-groups"
time="2020-03-02T16:10:12-08:00" level=error msg="Post https://openstack.domain.com:13000/v3/auth/tokens: x509: certificate signed by unknown authority"
time="2020-03-02T16:10:12-08:00" level=debug msg="Exiting deleting openstack routers"
```

# What you expected to happen?

As during cluster create, ca cert should be found from cloud config and used to trust endpoint. 

```yaml
# ~/.config/openstack/clouds-public.yaml
public-clouds:
  overcloud:
    auth_type: password
    identity_api_version: '3'
    cacert: '/Users/dlbewley/.config/openstack/ca.crt.pem'
    auth:
      auth_url: 'https://openstack.domain.com:13000/v3'
```

```yaml
# ~/.config/openstack/clouds.yaml
clouds:
  shiftstack:
    profile: overcloud
    auth:
      project_name: shiftstack
      user_domain_name: Default
      project_domain_name: Default
```

This has worked in the past, so I suspect something _may_ be off with my environment somehow, however nothing else seems amiss. `openstack` client is fine with same config.

# References

- #2997
