### ISSUE TITLE
install on openstack reading Cloud config fails at ConfigSecret   

### ISSUE THREAD

**Issue by admiyo** [openshift/installer#3361]
# Version

```console
$ openshift-install version
built from commit ddafb2d87d4744e56bd5d857621245311f186261
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:a6d7d861c10e7199d1f457973a54b06622d94c434b2876e09e56d578b08da0
```

# Platform:
Running on Fedora31 System against Mass Open Cloud
using
OCP 4.4 Nightly.  openshift-install-linux-4.4.0-0.nightly-2020-03-26-101622

OpenStack

# What happened?
./openshift-install create manifests --dir=rhfsi
INFO Credentials loaded from file "/home/ayoung/.config/openstack/clouds.yaml" 
INFO Consuming Install Config from target directory 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0x91cd84e]

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/manifests/openstack.CloudProviderConfigSecret(0xc001294460, 0xc0010c1ad0, 0xc000f7ceb0, 0x44, 0x50, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/manifests/openstack/cloudproviderconfig.go:30 +0x3e

Line in the code that failed is this:
29 func CloudProviderConfigSecret(cloud *clientconfig.Cloud) ([]byte, error) {
30 	domainID := cloud.AuthInfo.DomainID
31	if domainID == "" {

My Clouds.yaml file only had `user_domain_name` in it.  This is likely to be the norm.  However, adding `user_domain_id`  in does not fix the problem.  I suspect the issue is referencing the AuthInfo field, not DomainID

**Comment by pierreprinetti** [comment]
/label platform/openstack

The installer currently only supports username/password authentication. Does your `clouds.yaml` contain `auth.username` and `auth.password`? If this is the cause of the panic, we definitely want look into outputting an explicit error instead.

**Comment by admiyo** [comment]
It was a formate error...I had an older cloud.yaml format.  But it still should not stack trace.

**Comment by pierreprinetti** [comment]
In order to help me reproduce fast, can you please share (a censored version of) the clouds.yaml that triggered the panic?

**Comment by iamemilio** [comment]
We just resolved this on slack. We are going to leave this issue open because I would like to reference it as part of the installer validation and UX improvement epic. Getting seg faults due to an unsupported clouds.yaml format is very confusing and is not a customer experience that we want.

**Comment by iamemilio** [comment]
The root cause was an unsupported clouds.yaml format:

```yaml
clouds:
  mycloud:
    username: ...
    password: ...
    user_domain_name: ...
    identity_api_version: 3
    project_name: ...
    project_domain_name: ...
    #auth_url: ...
    auth_url:  ...
```

Gophercloud expects all clouds.yaml to be in the format:

```yaml
clouds:
  cloud_name:
    auth:
      ...
    region_name: ...
    interface: ...
    identity_api_version: ...
```

**Comment by adduarte** [comment]
hmm. I tested the clouds.yaml above: 
`clouds:
  mycloud:
    username: ...
    password: ...
    user_domain_name: ...
    identity_api_version: 3
    project_name: ...
    project_domain_name: ...
    #auth_url: ...
    auth_url:  ...
`
But only get error, no backtrace:

**Comment by thisismsreddy** [comment]
this worked for me 
```
clouds:
  devstack:
    auth:
      auth_url: http://192.168.122.10:5000
      identity_api_version: 3 
      project_name: admin
      user_domain_name: Default
      project_domain_name: Default 
      username: admin
      password: aaaaaaaaaaaaa
    region_name: RegionOne

```
