### ISSUE TITLE
Openstack: Master nodes unable to pull ocp-v4.0-art docker image

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [openshift/installer#3410]
# Version
4.4.0.rc4

# Platform:
Openstack

# What happened?

Hi, we are trying to deploy an installer provisioned openshift cluster on openstack. The issue that we are facing is that master nodes are unable to resolve any external URL using DNS server other than the default `10.0.0.6`, which is node DNS ip right ? 
Currently, this is our progress for the installation:
 
1. Infrastructure is created
2. Installer waits for bootstrap to complete(bootstrap node is set-up properly)
3. Master nodes fetch and consume ignition configs
4. Machine Config daemon runs on master nodes and try to set-up nodes. `machine-config-daemon-firstboot.service` and `machine-config-daemon-host.service` try to pull an [image](docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ba7b8a0f0a9d9a3420acefa2a569db9aab5d630d7c705c0f17df829e5badf3fd) and they fail. Because they can't ping https://quay.io/v2/

Error log from master node (machine-config-daemon-firstboot.service):
```
dev@sha256:ba7b8a0f0a9d9a3420acefa2a569db9aab5d630d7c705c0f17df829e5badf3fd: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ba7b8a0f0a9d9a3420acefa2a569db9aab5d630d7c705c0f17df829e5badf3fd: error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp 54.83.191.206:443: i/o timeout
```

I have tried various combinations, adding dns nameservers etc but nothing seems to work. This is the `resolve.conf` on master node:
```
# Generated by NetworkManager
search ipi.openshift.openstack.stakater.io
nameserver 10.0.0.6
nameserver 8.8.8.8
nameserver 8.8.4.4
```

The DNS resolution is working fine on `bootstrap` node btw. I looked further into it and found out that on `master node` it's able to reach and resolve `namesever` values and the corresponding addresses if and only if it's using the dns server 10.0.0.6. But if it tries to resolve using any other dns server it fails i.e. Google DNS etc.

The result of dig https://quay.io/v2/  : 
```
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> https://quay.io/v2/
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 36166
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a31eb56a6387886e (echoed)
;; QUESTION SECTION:
;https://quay.io/v2/.		IN	A
;; AUTHORITY SECTION:
.			21	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2020040300 1800 900 604800 86400
;; Query time: 1 msec
;; SERVER: 10.0.0.6#53(10.0.0.6)
;; WHEN: Fri Apr 03 10:02:15 UTC 2020
;; MSG SIZE  rcvd: 135
```

The result of dig +trace https://quay.io/v2/ : 
```
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> +trace https://quay.io/v2/
;; global options: +cmd
.			30	IN	NS	m.root-servers.net.
.			30	IN	NS	e.root-servers.net.
.			30	IN	NS	j.root-servers.net.
.			30	IN	NS	i.root-servers.net.
.			30	IN	NS	h.root-servers.net.
.			30	IN	NS	l.root-servers.net.
.			30	IN	NS	g.root-servers.net.
.			30	IN	NS	a.root-servers.net.
.			30	IN	NS	f.root-servers.net.
.			30	IN	NS	b.root-servers.net.
.			30	IN	NS	c.root-servers.net.
.			30	IN	NS	k.root-servers.net.
.			30	IN	NS	d.root-servers.net.
.			30	IN	RRSIG	NS 8 0 518400 20200415210000 20200402200000 48903 . AU9sY1rCEecwdjLh40JieJ/9OxB14pzeDa/ao3dqrW7QzWS8qQIsE+gm QfO0iFw/fMFjO6phfUsIrOXPECppO8aKwSGm4R2JegJp6DMmvu0Jc52F GC4KOjwxw2910FJLyMIrME9zeBtY/1OsR+A11GCggcHQGRnTdl0EYcIr v7vElrCmh1Kc69an6qxTDmDPwXTsoQzhRBDtPRm4k+0DaMjWdkCweX4u 76OLyMvYiFaBm955HG5fQaCkO6jHGyM1J8Zc7ZC5osQf3s6Hg554JKcL 0P1cY15mZzh+/B3k1Y5XiYBsTY2qyWdJZ0EyTVizsQeJT1cKssctDQN7 M6TkSA==
;; Received 717 bytes from 10.0.0.6#53(10.0.0.6) in 2 ms
;; connection timed out; no servers could be reached
```

Similarly `dig @8.8.8.8 https://quay.io/v2/` would fail. When it tries to curl it does that in a hierarchical order that is, it resolves `.` NS and then pick and use an NS from there and then resolve `.com.` similarly and repeats till it has resolved the URL. Whenever it changes the NS from `10.0.0.6`, it fails. 

# What you expected to happen?

For master nodes to be able to access external network.

# How to reproduce it (as minimally and precisely as possible)?

This is the `install-config.yaml` that we are using:

```yaml
apiVersion: v1
baseDomain: stakater.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: cluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    cloud: openstack
    computeFlavor: lb.large.1d
    externalDNS:
      - "8.8.8.8"
      - "8.8.4.4"
    externalNetwork: public-v4
    lbFloatingIP: 89.45.234.253
    octaviaSupport: "0"
    region: ""
    trunkSupport: "0"
publish: External
pullSecret: <concealed>
sshKey: <concealed>
```
Then we override the release image for install:

`export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="quay.io/openshift-release-dev/ocp-release@sha256:c05f74a898c7185de870edc1441865545441223a94b9f185a45ed2e020b38d16"`

And run installer:

`openshift-install create cluster --dir cluster --log-level debug`
