### ISSUE TITLE
RFE: install-config validation for CIDR overlap

### ISSUE THREAD

**Issue by therevoman** [openshift/installer#3436]
# Version
OpenShift v4+

# Platform:
ANY

# What happened?
Customer used overlapping CIDR's for network.clusterNetwork and network.machineNetwork
```networking:
  clusterNetwork:
  - cidr: 10.156.210.0/23
    hostPrefix: 25
  - cidr: 10.156.214.0/23
    hostPrefix: 25
  - cidr: 10.156.218.0/23
    hostPrefix: 25
  machineNetwork:
  - cidr: 10.156.208.0/23
  - cidr: 10.156.212.0/23
  - cidr: 10.156.216.0/23```

# What you expected to happen?
When the installer consumes this file the networks should be validated to ensure they do not overlap.  This could also be done before deleting the install-config.yaml


Enter text here.

# How to reproduce it (as minimally and precisely as possible)?
Create an install-config yaml file with a customized network section
execute `openshift-install create cluster`
Wait for provisioning to begin
Cluster creation will fail saying the openshift-sdn operator failed



# Anything else we need to know?



# References
Sorry, its internal Red Hat only
https://access.redhat.com/support/cases/#/case/02627379

**Comment by abhinavdahiya** [comment]
> from the original comment
```yaml
  clusterNetwork:
  - cidr: 10.156.210.0/23
    hostPrefix: 25
  - cidr: 10.156.214.0/23
    hostPrefix: 25
  - cidr: 10.156.218.0/23
    hostPrefix: 25
  machineNetwork:
  - cidr: 10.156.208.0/23
  - cidr: 10.156.212.0/23
  - cidr: 10.156.216.0/23
```

which CIDRs are overlapping, all of them seem separate to me? Maybe I'm missing something? @therevoman

**Comment by therevoman** [comment]
Looks like I copied the wrong example.  Those values are not overlapping.  But I think it would be nice to have a validation in place.

**Comment by abhinavdahiya** [comment]
> Looks like I copied the wrong example. Those values are not overlapping. But I think it would be nice to have a validation in place.

There is already validation in place.

```yaml
networking:
  clusterNetwork:
  - cidr: 10.156.210.0/23
    hostPrefix: 25
  - cidr: 10.156.214.0/23
    hostPrefix: 25
  - cidr: 10.156.218.0/23
    hostPrefix: 25
  machineNetwork:
  - cidr: 10.156.218.0/23
  - cidr: 10.156.212.0/23
  - cidr: 10.156.216.0/23
```

```
FATAL failed to fetch Install Config: failed to load asset "Install Config": invalid "install-config.yaml" file: networking.clusterNetwork[2].cidr: Invalid value: "10.156.218.0/23": cluster network must not overlap with any of the machine networks
```

/close
