### ISSUE TITLE
Failure to install OpenShift 4.4 on GCP with "Invalid value: \"internal\": failed to get network internal" error

### ISSUE THREAD

**Issue by pavelzagalsky-paloalto** [openshift/installer#3651]
# Version

```console
$ openshift-install version
./openshift-install 4.4.4
built from commit 0c7f28d8642b8e9bf330038423120c5cf6a4bf91
release image quay.io/openshift-release-dev/ocp-release@sha256:baa687f29b0ac155d8f4c6914056d36d68f343feb9c1e82b46eef95819d00be5
```

# Platform:

# What happened?
Failing to install OpenShift v4.4 on GCP with the following error:

level=fatal msg="failed to fetch Terraform Variables: failed to load asset \"Install Config\": platform.gcp.network: Invalid value: \"internal\": failed to get network internal: Get https://www.googleapis.com/compute/v1/projects/my-project/global/networks/internal?alt=json&prettyPrint=false: context canceled"

# What you expected to happen?

Expected a successful installation. The same yaml works flawlessly with OpenShift 4.3

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./openshift-install create cluster --dir=openshift_installations/openshift_workspace --log-level=debug
```

# Anything else we need to know?

Here's my edited install-config.yaml

```
--- 
apiVersion: v1
baseDomain: openshift.internal
compute: 
  - 
    architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform: 
      gcp: 
        type: n1-standard-4
        zones: 
          - us-central1-a
    replicas: 3
controlPlane: 
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: 
    gcp: 
      type: n1-standard-8
      zones: 
        - us-central1-a
  replicas: 2
metadata: 
  creationTimestamp: ~
  name: automation-openshift-237695
networking: 
  clusterNetwork: 
    - 
      cidr: 10.0.0.0/14
      hostPrefix: 23
  machineNetwork: 
    - 
      cidr: 10.10.197.0/24
  networkType: OpenShiftSDN
  serviceNetwork: 
    - 10.30.0.0/16
platform: 
  gcp: 
    computeSubnet: internal-automation
    controlPlaneSubnet: internal-automation
    network: internal
    projectID:my-project
    region: us-central1
publish: Internal
pullSecret: "<pullSecret>"
sshKey: "sshKey"
```
openshift-install.log:

time="2020-05-25T10:49:31+03:00" level=debug msg="OpenShift Installer 4.4.4"
time="2020-05-25T10:49:31+03:00" level=debug msg="Built from commit 0c7f28d8642b8e9bf330038423120c5cf6a4bf91"
time="2020-05-25T10:49:31+03:00" level=debug msg="Fetching Terraform Variables..."
time="2020-05-25T10:49:31+03:00" level=debug msg="Loading Terraform Variables..."
time="2020-05-25T10:49:31+03:00" level=debug msg="  Loading Cluster ID..."
time="2020-05-25T10:49:31+03:00" level=debug msg="    Loading Install Config..."
time="2020-05-25T10:49:31+03:00" level=debug msg="      Loading SSH Key..."
time="2020-05-25T10:49:31+03:00" level=debug msg="      Loading Base Domain..."
time="2020-05-25T10:49:31+03:00" level=debug msg="        Loading Platform..."
time="2020-05-25T10:49:31+03:00" level=debug msg="      Loading Cluster Name..."
time="2020-05-25T10:49:31+03:00" level=debug msg="        Loading Base Domain..."
time="2020-05-25T10:49:31+03:00" level=debug msg="        Loading Platform..."
time="2020-05-25T10:49:31+03:00" level=debug msg="      Loading Pull Secret..."
time="2020-05-25T10:49:31+03:00" level=debug msg="      Loading Platform..."
time="2020-05-25T10:49:31+03:00" level=info msg="Credentials loaded from gcloud CLI defaults"
time="2020-05-25T10:49:31+03:00" level=fatal msg="failed to fetch Terraform Variables: failed to load asset \"Install Config\": platform.gcp.network: Invalid value: \"internal\": failed to get network internal: Get https://www.googleapis.com/compute/v1/projects/test-247119/global/networks/internal?alt=json&prettyPrint=false: context canceled"
