### ISSUE TITLE
Vsphere install -- POD and Service network 

### ISSUE THREAD

**Issue by eselvam** [openshift/installer#3724]
# Version
4.4.3
```console
$ openshift-install version
4.4.3
```

# Platform:

# What happened?

How the POD and service network address are allocated to Openshift. We specify these details in baremetal but not available in vsphere install - install-config.yaml file. Please explain.

# What you expected to happen?

can We specify Pod and service network details in install-config.yaml file for vsphere?

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by jurica-zrna** [comment]
You can do it the same way it's done on bare metal:
```
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
```
