### ISSUE TITLE
Vsphere IPI fails - can't provision worker nodes.

### ISSUE THREAD

**Issue by stobias123** [openshift/installer#3824]
# Version

```console
$ openshift-install version
[root@c7ee65750e9d data]# openshift-install version
openshift-install 4.5.0-0.nightly-2020-06-05-214616
built from commit 5a90620ee0c6316e4137a75d4eea18b21a87fd3f
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:49e27e4673dc578d5f8118ee16bf695aabb750d309f4425d52e121b80e4e7870
```

# Platform:
vsphere - IPI

# What happened?

Masters all came online, but the cluster got stuck after that.

Some digging found that worker machines were stuck trying to provision, b/c they couldn't find the resource pool.

```
$ k logs -f machine-api-controllers-684f5ffddd-lxw2w -n openshift-machine-api -c machine-controller
...
mgmt-r4z8k-worker-mg5mt: failed to create machine: unable to get resource pool for <nil>: default resource pool resolves to multiple instances, please specify
```

# What you expected to happen?

Either prompt me for resource pool in the initial config, or configure the proper resource pool.

# How to reproduce it (as minimally and precisely as possible)?
IPI install - have multiple resource pools available. 

One of my resource pools on this cluster was called `default` - not sure if related.

# Anything else we need to know?

Resolved by editing the worker machine set as shown below.

```yaml
spec:
  ..
  providerSpec:
  ..
      workspace:
        datacenter: vcf-dc01
        datastore: vcf-vsan
        resourcePool: myResourcePool # <- This line was added
        folder: /vcf-dc01/vm/mgmt-r4z8k
        server: vcf-vc01.vcf.foobar.io
```
# References

Slack discussion here -> https://kubernetes.slack.com/archives/C6BRQSH2S/p1593553476264800
