### ISSUE TITLE
installation openshift IPI 

### ISSUE THREAD

**Issue by muhammad50** [openshift/installer#3932]
# Version 4.5

```console
$ openshift-install version
<your output here>
```

# Platform:

# What happened?
when we start installation he ask me about 
Virtual IP Address for API 
Virtual IP Address for Ingress 
i need to enplane for this two IPs ? 

# What you expected to happen?

i do not knew what this two IPs point for which machine

**Comment by bshephar** [comment]
Hi, 

Not a lot of info to go off here. What platform are you installing on?

For example, with OpenStack, the IP for API defaults to 10.0.0.5 as the fixed IP address, and that gets a Floating IP address assigned to it as defined here:

```
platform:
  openstack:
    apiVIP: 10.0.0.5
    cloud: shiftstack
    computeFlavor: ocp8vcpus
    externalDNS: null
    externalNetwork: external_network
    ingressVIP: 10.0.0.7
    lbFloatingIP: 10.x.x.135
    octaviaSupport: "1"
    region: ""
    trunkSupport: "1"

```

So the lbFloatingIP will be the floating IP address that I reach from my laptop for example.

And you can see the ingressVIP in my output above as well. Which by default is 10.0.0.7
