### ISSUE TITLE
RFE: Support for hugepages (2Mb, 1G, etc..) on libvirt

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/installer#3976]
Hi,

On my hypervisors (RHEL), I have most of the memory dedicated to hugepages (the default 2Mb hugepages).
This allows me to fit more VMs into reserved memory and makes their TLB's smaller (needed when you have 64Gb or more memory).

Here's an example:
```
# virsh dumpxml sat6|head -24
<domain type='kvm' id='3'>
  <name>sat6</name>
[...]
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
[...]
```
(The above is for the default 2mb hugepages, for 1G hugepages the syntax is slightly different).

I've done some research and it appears that Terraform has support for hugepages but I wouldn't know where to change it in the openshift installer..
Do you have any idea of where that might be?
Any hint would be welcomed..

**Comment by abhinavdahiya** [comment]
> I've done some research and it appears that Terraform has support for hugepages

If you can provide how to represent the required configuration in terraform template example, i can help guide you where to make that change.

**Comment by ElCoyote27** [comment]
I'm not too sure how it would look in Terraform.

If I look at the manifests:
```
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4b-b4m6c
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: ocp4b-b4m6c-worker-0
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4b-b4m6c
      machine.openshift.io/cluster-api-machineset: ocp4b-b4m6c-worker-0
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4b-b4m6c
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp4b-b4m6c-worker-0
    spec:
      metadata:
        creationTimestamp: null
      providerSpec:
        value:
          apiVersion: libvirtproviderconfig.openshift.io/v1beta1
          autostart: false
          cloudInit: null
          domainMemory: 7168  <====================================================
          domainVcpu: 4 <====================================================
          ignKey: ""
          ignition:
            userDataSecret: worker-user-data
          kind: LibvirtMachineProviderConfig
          networkInterfaceAddress: 192.168.126.0/24
          networkInterfaceHostname: ""
          networkInterfaceName: ocp4b-b4m6c
          networkUUID: ""
          uri: qemu+tcp://172.18.0.1/system
          volume:
            baseVolumeID: ocp4b-b4m6c-base
            poolName: ocp4b-b4m6c
            volumeName: ""
status:
  replicas: 0

```

and looking at at the terraform source from the upstream repo:
```
[root@daltigoth /opt/OCP-4/go/src]# grep -r Hugepages
Binary file github.com/openshift/installer/bin/openshift-install matches
github.com/openshift/installer/pkg/terraform/exec/plugins/vendor/github.com/libvirt/libvirt-go-xml/domain.go:type DomainMemoryHugepages struct {
github.com/openshift/installer/pkg/terraform/exec/plugins/vendor/github.com/libvirt/libvirt-go-xml/domain.go:   Hugepages []DomainMemoryHugepage `xml:"page"`
github.com/openshift/installer/pkg/terraform/exec/plugins/vendor/github.com/libvirt/libvirt-go-xml/domain.go:   MemoryHugePages    *DomainMemoryHugepages    `xml:"hugepages"`
```

so I would assume that something like this would work:
Hugepages: 1024

I don't know enough OpenShift to figure if I could update a Spec to change that in the openshift-machine-api running on my OCP cluster on libvirt.
