### ISSUE TITLE
failed to create cluster using vsphere IPI

### ISSUE THREAD

**Issue by thiguetta** [openshift/installer#4041]
# Version

```console
$ openshift-install version
4.5.5
```

# Platform:
vSphere IPI

# What happened?

created a cluster using the specifications in https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installing-vsphere-installer-provisioned but only  master nodes came up, cluster failed to wait to compute nodes which never got created.

# What you expected to happen?
it was expected the cluster (master and workers) to be up

# How to reproduce it (as minimally and precisely as possible)?

1. created DNS records for API and apps
2. download the latest version of installer https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/
3. run `openshift-install create cluster`
4. fulfill with my infrastructure information

```console
level=info msg="Waiting up to 30m0s for the cluster at https://api.ocp-cluster1.portworx.dev:6443 to initialize..."
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 68% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: downloading update"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 0% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 10% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 12% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 61% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 70% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 75% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 82% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 83% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 84% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 85% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 85% complete, waiting on authentication, cluster-autoscaler, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, machine-api, machine-config, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 85% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete, waiting on authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete, waiting on authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete"
level=debug msg="Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: downloading update"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 2% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 9% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 13% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete, waiting on authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.5: 86% complete"
level=error msg="Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingEndpoints::RouteStatus_FailedHost: IngressStateEndpointsDegraded: No endpoints found for oauth-server\nRouteStatusDegraded: route is not available at canonical host oauth-openshift.apps.ocp-cluster1.portworx.dev: []"
level=info msg="Cluster operator authentication Progressing is Unknown with NoData: "
level=info msg="Cluster operator authentication Available is Unknown with NoData: "
level=info msg="Cluster operator console Progressing is True with DefaultRouteSync_FailedAdmitDefaultRoute::OAuthClientSync_FailedHost: DefaultRouteSyncProgressing: route \"console\" is not available at canonical host []\nOAuthClientSyncProgressing: route \"console\" is not available at canonical host []"
level=info msg="Cluster operator console Available is Unknown with NoData: "
level=info msg="Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available."
level=info msg="Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available."
level=error msg="Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: default"
level=info msg="Cluster operator insights Disabled is False with : "
level=info msg="Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available"
level=info msg="Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack."
level=error msg="Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager Route to become ready failed: waiting for RouteReady of alertmanager-main: no status available for alertmanager-main"
level=info msg="Cluster operator monitoring Available is False with : "
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Can you include the must-gather ?
https://docs.openshift.com/container-platform/4.5/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data

That should help triage the issue.

Since the compute nodes are getting created i would start debugging that, 

- look at the state of the machines oc get mahines -n openshift-machine-api
- look at failure in the machine-api controllers if the machine object doesn't have one, look at the logs from the pods for machine-controllers in namespace openshift-machine-api
- If the backing VM have been created, take a look at the CSRs that maybe be pending, oc get csr
- Then we can look at the logs for the cluster machine approver in openshift-cluster-machine-approver namespace.

That should help narrow why no compute nodes joined the cluster.

**Comment by kevydotvinu** [comment]
Check whether you have created a correct API VIP and Ingress VIP A record in DNS.

**Comment by fredrik-furtenbach** [comment]
@thiguetta did you solve this? I have the exact same problem.

**Comment by phlbrz** [comment]
Also for me. Everything is up, but my cluster is displaying this message and cannot update.

```

Conditions
TypeStatusUpdatedReasonMessage
AvailableTrue
Oct 25, 4:20 am
-desired and current number of IngressControllers are equal
ProgressingFalse
Oct 25, 4:20 am
-desired and current number of IngressControllers are equal
DegradedTrue
Oct 25, 2:42 am
IngressControllersDegradedSome ingresscontrollers are degraded: default

Operand Versions
Name | Version
-- | --
operator | 4.5.15
ingress-controller | quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:01a749bd3a30fb059659309a18a4c9376e24d8044c42cbb893566d49a50036c1


```

![Screenshot from 2020-10-26 19-05-44](https://user-images.githubusercontent.com/6169365/97233801-527bc400-17be-11eb-87c7-a69bbd5ec7ad.png)

**Comment by phlbrz** [comment]
Alright, after reading a lot, found some interesting correlation about the documentation to solve my problem.

Error and success:

```
2020-10-27T02:22:16.035Z	INFO	operator.ingress_controller	ingress/controller.go:165	reconciling	{"request": "openshift-ingress-operator/default"}
2020-10-27T02:22:16.105Z	ERROR	operator.ingress_controller	ingress/controller.go:232	got retryable error; requeueing	{"after": "1m0s", "error": "IngressController is degraded: LoadBalancerReady=False"}
2020-10-27T02:22:16.105Z	INFO	operator.status_controller	status/controller.go:90	Reconciling	{"request": "openshift-ingress-operator/default"}
2020-10-27T02:22:16.105Z	INFO	operator.ingress_controller	ingress/controller.go:165	reconciling	{"request": "openshift-ingress-operator/default"}
2020-10-27T02:22:16.114Z	DEBUG	operator.init.controller-runtime.controller	controller/controller.go:282	Successfully Reconciled	{"controller": "status_controller", "request": "openshift-ingress-operator/default"}
```
This one helped me https://docs.openshift.com/container-platform/4.5/post_installation_configuration/network-configuration.html#private-clusters-setting-dns-private_post-install-network-configuration 

This one helped me to find `<infrastructureID>` https://docs.openshift.com/container-platform/4.5/machine_management/creating-infrastructure-machinesets.html#machineset-yaml-osp_creating-infrastructure-machinesets

```
oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
```
Now it shows another error

```
spec:
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
    type: LoadBalancerService
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-10-25T05:41:38Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2020-10-25T07:20:28Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-25T07:20:28Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "False"
    type: DeploymentDegraded
  - lastTransitionTime: "2020-10-25T05:41:41Z"
    message: The endpoint publishing strategy supports a managed load balancer
    reason: WantedByEndpointPublishingStrategy
    status: "True"
    type: LoadBalancerManaged
  - lastTransitionTime: "2020-10-25T05:41:41Z"
    message: The LoadBalancer service is pending
    reason: LoadBalancerPending
    status: "False"
    type: LoadBalancerReady
  - lastTransitionTime: "2020-10-27T02:22:16Z"
    message: DNS management is supported and zones are specified in the cluster DNS
      config.
    reason: Normal
    status: "True"
    type: DNSManaged
  - lastTransitionTime: "2020-10-25T05:46:23Z"
    message: 'One or more other status conditions indicate a degraded state: LoadBalancerReady=False'
    reason: DegradedConditions
    status: "True"
    type: Degraded
  - lastTransitionTime: "2020-10-27T02:22:16Z"
    message: The wildcard record resource was not found.
    reason: RecordNotFound
    status: "False"
    type: DNSReady
  domain: apps.idocp4.domain.com
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
    type: LoadBalancerService
  observedGeneration: 3

```
