### ISSUE TITLE
[Feature Request] external service network via install-config.yaml

### ISSUE THREAD

**Issue by Elyytscha** [openshift/installer#4275]
# Version

```console
$ openshift-install version
4.5.6
```

# Platform:
all

Please specify:
all

# What would be nice to have?

its not possible to set the external service network ip range at install via install-config, it would be nice to be able to set this range in the install-config.yaml like so:

(i know i could just hack the manifests for this, but would be a lot easier with support by the install-config.yaml)

```
# install-config.yaml
...
metadata:
  name:  okd
networking:
  clusterNetworks:
  - cidr: 10.10.0.0/16
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 10.20.0.0/16
  externalIP:
    autoAssignCIDRs:
    - 10.30.0.0/16
    policy:
      allowedCIDRs:
      -  10.30.0.0/16
...
```
