### ISSUE TITLE
Vsphere DNS Resolution behavior different in 4.7 than 4.6?

### ISSUE THREAD

**Issue by DanPhonovation** [openshift/installer#4714]
I'm on VSphere 7/ESX6.7

Latest 4.7 OKD.

It appears, unlike 4.6 - 4.7 somehow thinks my vsphere server is the api vip?

My attemped config & procedure is the same on both. 4.6 succeeds in creating workers. 4.7 does not. 

The DNS server remains the same in both cases. Yet 4.7 decides to resolve it to the api VIP per the logs?

```
ERROR Cluster operator storage Degraded is True with VSphereProblemDetectorController_SyncError: VSphereProblemDetectorControllerDegraded: failed to connect to vsphere1.vdev.local: Post "https://vsphere1.vdev.local/sdk": dial tcp 10.1.88.10:443: connect: connection refused
```
This despite the fact that from the master/control node itself:

```
[root@provisioner okd47try2]# nslookup vsphere1.vdev.local

Server: 10.1.88.2

Address: 10.1.88.2#53
Name: vsphere1.phono-vdev.local

Address: 10.1.71.200
```

10.1.71.200 is correct.

**Comment by staebler** [comment]
Would you mind providing the install-config.yaml that you are using to install this cluster?

The in-cluster pods will use a different DNS than the VM itself does. You could try to do an `oc debug` into one of the machines, and do the nslookup from there to see the difference.

**Comment by DanPhonovation** [comment]
You're kind. Thanks.

Here is install-config.yaml - nothing special. Completely odd that the same set of machines in 4.6 resolves it fine against my DNSMasq but this doesn't. config was the same in both.


```
[root@provisioner okd47try2]# cat ~/install-config.yaml
apiVersion: v1
baseDomain: k8.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 24576
      osDisk:
        diskSizeGB: 80
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 24576
      osDisk:
        diskSizeGB: 80
  replicas: 3
metadata:
  creationTimestamp: null
  name: okdcluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.1.88.10
    cluster: NEIR-TEST
    datacenter: MyDataCentre
    defaultDatastore: ESX_LocalStore
    ingressVIP: 10.1.88.20
    network: K8
    password: ***************
    username: administrator@vsphere.local
    vCenter: vsphere1.vdev.local
publish: External
pullSecret:
```






Since this is a "system container" (machine-processor or api?) - how do I oc debug enter it to try from it? N00b here.
