### ISSUE TITLE
Worker nodes stuck in provisioned state on GCP

### ISSUE THREAD

**Issue by sachingade20** [openshift/installer#4936]
# Version

```console
$ openshift-install version
./openshift-install 4.5.35
built from commit e30ca92797532d9f0e0c56aac20aad27e594ab43
release image quay.io/openshift-release-dev/ocp-release@sha256:ea89ed06f4a5c38dde36f053b250df4bab184729c1adf60afa43d0de8b1930f3
```

# Platform: 
GCP
IPI (automated install with openshift-install.)

Installed with quick start guide 
https://docs.openshift.com/container-platform/4.5/installing/installing_gcp/installing-gcp-default.html

# What happened?

Team we are trying to setup Openshift Container Platform on GCP project "XXXX" using steps mentioned in document

https://docs.openshift.com/container-platform/4.5/installing/installing_gcp/installing-gcp-default.html

Our GCP installation is failing with error.
```
time="2021-04-27T07:09:05Z" level=fatal msg="failed to initialize the cluster: Working towards 4.5.35: 86% complete, waiting on authentication, console, image-registry, ingress, kube-storage-version-migrator, monitoring"
```

When i debugged more i found out worker nodes are stuck in provisioned state and not becoming nodes.
```
➜  ~ oc get nodes
NAME                                                         STATUS   ROLES    AGE   VERSION
ocp-sda-cluster-g4wtj-master-0.c.flow-on-k8s-test.internal   Ready    master   22m   v1.18.3+cdb0358
ocp-sda-cluster-g4wtj-master-1.c.flow-on-k8s-test.internal   Ready    master   22m   v1.18.3+cdb0358
ocp-sda-cluster-g4wtj-master-2.c.flow-on-k8s-test.internal   Ready    master   22m   v1.18.3+cdb0358
➜  ~ oc get machines -n openshift-machine-api
NAME                                   PHASE         TYPE            REGION        ZONE            AGE
ocp-sda-cluster-g4wtj-master-0         Running       n2-standard-4   us-central1   us-central1-a   22m
ocp-sda-cluster-g4wtj-master-1         Running       n2-standard-4   us-central1   us-central1-c   22m
ocp-sda-cluster-g4wtj-master-2         Running       n2-standard-4   us-central1   us-central1-a   22m
ocp-sda-cluster-g4wtj-worker-a-t9k4h   Provisioned   n2-standard-4   us-central1   us-central1-a   8m37s
ocp-sda-cluster-g4wtj-worker-a-x8w9m   Provisioned   n2-standard-4   us-central1   us-central1-a   8m37s
ocp-sda-cluster-g4wtj-worker-c-sk9t9   Provisioned   n2-standard-4   us-central1   us-central1-c   8m37s
ocp-sda-cluster-g4wtj-worker-c-v4lm8   Provisioned   n2-standard-4   us-central1   us-central1-c   8m37s
➜  ~ gcoc getomsr
NAME        AGE     SIGNERNAME                                    REQUESTOR                                                                   CONDITION
csr-24rtj   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-2vtwz   4m38s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-657h7   4m38s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-74ptq   22m     kubernetes.io/kubelet-serving                 system:node:ocp-sda-cluster-g4wtj-master-0.c.flow-on-k8s-test.internal      Approved,Issued
csr-7xxs5   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-bcrkh   22m     kubernetes.io/kubelet-serving                 system:node:ocp-sda-cluster-g4wtj-master-1.c.flow-on-k8s-test.internal      Approved,Issued
csr-drd58   4m54s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-fzvzw   22m     kubernetes.io/kubelet-serving                 system:node:ocp-sda-cluster-g4wtj-master-2.c.flow-on-k8s-test.internal      Approved,Issued
csr-s4fqp   4m54s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-vnrds   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
➜  ~ oc logs -f machine-api-controllers-76c494db9-dfbh9 -n openshift-machine-api -c machine-controller | grep failed
W0513 07:28:57.493180       1 controller.go:315] ocp-sda-cluster-g4wtj-worker-c-sk9t9: failed to create machine: requeue in: 20s
E0513 07:28:58.213347       1 controller.go:279] ocp-sda-cluster-g4wtj-master-0: error updating machine: [machinescope] failed to patch machine "ocp-sda-cluster-g4wtj-master-0" in namespace "openshift-machine-api": Operation cannot be fulfilled on machines.machine.openshift.io "ocp-sda-cluster-g4wtj-master-0": the object has been modified; please apply your changes to the latest version and try again
E0513 07:28:58.213391       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="[machinescope] failed to patch machine \"ocp-sda-cluster-g4wtj-master-0\" in namespace \"openshift-machine-api\": Operation cannot be fulfilled on machines.machine.openshift.io \"ocp-sda-cluster-g4wtj-master-0\": the object has been modified; please apply your changes to the latest version and try again"  "controller"="machine_controller" "request"={"Namespace":"openshift-machine-api","Name":"ocp-sda-cluster-g4wtj-master-0"}
W0513 07:29:00.993210       1 controller.go:315] ocp-sda-cluster-g4wtj-worker-a-x8w9m: failed to create machine: requeue in: 20s
W0513 07:29:02.667147       1 controller.go:315] ocp-sda-cluster-g4wtj-worker-a-t9k4h: failed to create machine: requeue in: 20s
W0513 07:29:04.595759       1 controller.go:315] ocp-sda-cluster-g4wtj-worker-c-v4lm8: failed to create machine: requeue in: 20s
```
# What you expected to happen?

Worker should  get running and oc get nodes should  show it ready.

# How to reproduce it (as minimally and precisely as possible)?

https://docs.openshift.com/container-platform/4.2/installing/installing_gcp/installing-gcp-default.html

create gcp project
create service account
give permissions mentioned in document
Service Account have below permisssions
```
Compute Admin
Deployment Manager Editor
DNS Administrator
Security Admin
Service Account Admin
Service Account Key Admin
Service Account User
Storage Admin
```
create install-config.yaml
#### openshift-cluster/install-config.yaml  ####
```
apiVersion: v1
baseDomain: REDACTED
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    gcp:
      type: n2-standard-4
      zones:
      - us-central1-a
      - us-central1-c
      osDisk:
        diskType: pd-ssd
        diskSizeGB: 256
  replicas: 3
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    gcp:
      type: n2-standard-4
      zones:
      - us-central1-a
      - us-central1-c
      osDisk:
        diskType: pd-standard
        diskSizeGB: 128
  replicas: 3
metadata:
  name: REDACTED
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: REDACTED
    region: REDACTED
fips: false
pullSecret: REDACTED
sshKey: REDACTED
####
```

```console
$ mkdir openshift-cluster
$ vim  openshift-cluster/install-config.yaml # put above config in file and save
$./openshift-install create cluster --dir=openshift-cluster --log-level=debug

```
installation failed and only master nodes are ready  worker nodes stuck in provisioned state. 
# Anything else we need to know?
