### ISSUE TITLE
Openstack IPI: Validate API and Ingress VIPs are not the same

### ISSUE THREAD

**Issue by gyohuangxin** [openshift/installer#4945]
# Platform:

openstack

IPI

# What happened?
There is no validation for API and Ingress vips, so users can input the same vips.
```
platform:
  openstack:
    machinesSubnet: 47f667b6-9fd5-45ca-8a97-ea90ce98c04b
    apiVIP: 172.26.105.28
    ingressVIP: 172.26.105.28
    cloud: openstack
    computeFlavor: m1.medium
    octaviaSupport: "0"
    region: ""
```
Need validate API and Ingress VIPs are not the same.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.
