### ISSUE TITLE
How to add azure credentials to the install-config.yaml file?

### ISSUE THREAD

**Issue by anraghun** [openshift/installer#4981]
Hi,

The readme file states that the `install-config.yaml` file can be leveraged to bypass prompts in a non interactive environment. However, when I run `openshift-install create install-config`, it doesn't prompt me for the azure credentials such as service principal client ID and secret, the subscription or the tenant ID. It generates the following `install-config.yaml`:

```
apiVersion: v1
baseDomain: example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: azure
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: azure
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp-test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: test-rg
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: eastus
publish: External
pullSecret:
```

Where can I add the above credentials in this config file?
