### ISSUE TITLE
Installer May Be Ignoring Mulitple Settings in install-config.yml

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#545]
My install config:

```
    machines:
    - name: master
      platform:
        aws:
          iamRoleName: ""
          rootVolume:
            iops: 100
            size: 22
            type: gp2
          type: m4.large
      replicas: 3
    - name: worker
      platform:
        aws:
          iamRoleName: ""
          rootVolume:
            iops: 100
            size: 22
            type: gp2
          type: m4.large
      replicas: 5
```

My masters were created as type t2.medium, and the root volume is 30 GB in size. Suspect multiple settings in here are not being applied.

Workers get the correct type, but their root volume section appears to have no effect either.

**Comment by dgoodwin** [comment]
This problem may actually be much broader. It  looks like you will be prompted for at least admin password, email, base domain, despite them being in the install config.

Example:

```
data:                                                                                                                                                                                     [13/3190]
  install-config.yml: |
    admin:
      email: dgoodwin@redhat.com
      password: letmein
      sshKey: REDACTED
    baseDomain: new-installer.openshift.com
    clusterID: a9dfbd60-1b52-498b-9703-932c1eea347a
    machines:
    - name: master
      platform:
        aws:
          iamRoleName: ""
          rootVolume:
            iops: 100
            size: 22
            type: gp2
          type: m4.large
      replicas: 3
    - name: worker
      platform:
        aws:
          iamRoleName: ""
          rootVolume:
            iops: 100
            size: 22
            type: gp2
          type: m4.large
      replicas: 5
    metadata:
      creationTimestamp: null
      name: dgoodwin1
    networking:
      podCIDR: 10.2.0.0/16
      serviceCIDR: 10.3.0.0/16
      type: flannel
    platform:
      aws:
        region: us-east-1
        vpcCIDRBlock: 10.0.0.0/16
        vpcID: ""
    pullSecret: 'REDACTED'
```

If I then run in a pod without specifying the old env vars:

```
time="2018-10-26T16:59:19Z" level=info msg="running openshift-install"
level=debug msg="Fetching \"Terraform Variables\"..."
level=debug msg="Fetching dependencies of \"Terraform Variables\"..."
level=debug msg="  Fetching \"Install Config\"..."
level=debug msg="  Fetching dependencies of \"Install Config\"..."
level=debug msg="    Fetching \"Cluster ID\"..."
level=debug msg="    Generating \"Cluster ID\"..."
level=debug msg="    Fetching \"Email Address\"..."
level=debug msg="    Generating \"Email Address\"..."
level=debug msg="    Fetching \"Password\"..."
level=debug msg="    Generating \"Password\"..."
level=debug msg="    Fetching \"SSH Key\"..."
level=debug msg="    Generating \"SSH Key\"..."
level=debug msg="    Fetching \"Base Domain\"..."
level=debug msg="    Generating \"Base Domain\"..."
level=fatal msg="Error executing openshift-install: EOF"
? Base Domain [? for help]                                                                                                                                                                        time="2018-10-26T16:59:19Z" level=error msg="error capturing openshift-install stdout" error="read |0: file already closed"
^[[48;195Rtime="2018-10-26T16:59:19Z" level=error msg="error capturing openshift-install stderr" error="read |0: file already closed"
time="2018-10-26T16:59:19Z" level=error msg="error running openshift-install" error="exit status 1"
```
