### ISSUE TITLE
IPI OpenShift Cluster Deployment Failed Due To Quotas

### ISSUE THREAD

**Issue by ecda909** [openshift/installer#5491]
# Version
```
./openshift-install 4.9.9
built from commit 1c538b8949f3a0e5b993e1ae33b9cd799806fa93
release image quay.io/openshift-release-dev/ocp-release@sha256:dc6d4d8b2f9264c0037ed0222285f19512f112cc85a355b14a66bd6b910a4940
release architecture amd64
```

# Platform:
Please specify the platform type: aws

Please specify:
* IPI - Installer provisioned luster 

# What happened?
All of our installer resources are set and everything is within a designated directory (openshift-installation). I ran the cli command to generate the install-config:

```./openshift-install create install-config --dir openshift-installation/```

and then ran the command to install and initialize the cluster:

```./openshift-install create cluster --log-level=info --dir openshift-installation```

Then I received this error:

```FATAL failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Quota Check": error(MissingQuota): ec2/L-0263D0A3 is not available in us-east-1 because the required number of resources (6) is more than the limit of 5```

# What you expected to happen?

I've looked up the service limit requirements here: https://docs.openshift.com/rosa/rosa_getting_started/rosa-required-aws-service-quotas.html and have cross-referenced them with the ones we have and it looks like we have all of the default limits set accordingly. I expect for this deployment to deploy with the standard limits that are already set within our account (default). e.g. this deployment is giving an error stating that we have only met the default number of EIPs - VPC EIPs limits and are in need of at least 6 as opposed to the 5 we have. How do I configure our config so that our deployment completes successfully with the standard limits? 

Side Note: The number of Control Plane and worker nodes are not important at this time...

install-config.yaml
```
apiVersion: v1
baseDomain: <dns_name>.org
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
credentialsMode: Mint
metadata:
  creationTimestamp: null
  name: <name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
publish: External
pullSecret: <secret_here>
```

# How to reproduce it (as minimally and precisely as possible)?

1. Download and configure the openshift installer
2. Create a directory named: openshift-installation
3. Run the command ./openshift-install create install-config --dir openshift-installation/
4. Run the command ./openshift-install create cluster --log-level=info --dir openshift-installation

Thanks!
