### ISSUE TITLE
Open Shift deployment not deploying With compute.platform.aws.iamRole IAM Role 

### ISSUE THREAD

**Issue by ecda909** [openshift/installer#5502]
# Version
```
./openshift-install 4.9.9
built from commit 1c538b8949f3a0e5b993e1ae33b9cd799806fa93
release image quay.io/openshift-release-dev/ocp-release@sha256:dc6d4d8b2f9264c0037ed0222285f19512f112cc85a355b14a66bd6b910a4940
release architecture amd64
```

# Platform:
Please specify the platform type: aws

Please specify:
* IPI - Installer provisioned luster 

# What happened?
All of our installer resources are set and everything is within a designated directory (openshift-installation). I ran the cli command to generate the install-config:

```./openshift-install create install-config --dir openshift-installation/```

and then ran the command to install and initialize the cluster:

```./openshift-install create cluster --log-level=info --dir openshift-installation```

Then I received this error:

```
Error: Error creating IAM Role <role_name>: AccessDenied: User: arn:aws:iam::<arn_number>:user/<user> is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::<arn_number>:role/<role_name>
```

# What you expected to happen?

In the install-config, I have the compute.platform.aws.iamRole path set to the specific IAM role that Open Shift is trying to create for the masters and workers. We need to use this because we are required to have an IAM boundary set in order for us to create new roles. I think this is the right way to do this, however whenever I deploy via the config, I get an error for another role that needs to be created. The config doesn't allow for an array in that key-value pair (e.g. iamRole: ["role_name","role_name"]), so what should I do? I expect the cluster to deploy instances attached with the IAM role I have created with the boundary. 

install-config.yaml
```
apiVersion: v1
baseDomain: <dns_name>
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones: ["us-east-1a","us-east-1b","us-east-1c"]
      iamRole: "role_name"
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones: ["us-east-1a","us-east-1b","us-east-1c"]
  replicas: 3
credentialsMode: Mint
metadata:
  creationTimestamp: null
  name: <name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
    iamRole: "role_name"
publish: External
pullSecret:
```

# How to reproduce it (as minimally and precisely as possible)?

1. Download and configure the openshift installer
2. Create a directory named: openshift-installation
3. Run the command ./openshift-install create install-config --dir openshift-installation/
4. Run the command ./openshift-install create cluster --log-level=info --dir openshift-installation

Thanks!
