### ISSUE TITLE
vsphere ipi ignoring resourcePool setting in install-config.yaml

### ISSUE THREAD

**Issue by nate-duke** [openshift/installer#5537]
# Version

```console
❯ openshift-install version
openshift-install 4.9.0-0.okd-2021-12-12-025847
built from commit 96418c49a7761dc0a299bc083795a771df9ef789
release image quay.io/openshift/okd@sha256:4323eccc8c7cf782ff632a3c8ddf783b3f971af52e1b4bdcb93ab9127ed0be57
release architecture amd64
```

# Platform:
vsphere ipi

# What happened?
systems were provisioned without configured resourcePool

# What you expected to happen?
systems to be provisioned with configured resourcePool

# How to reproduce it (as minimally and precisely as possible)?
create minimal install-config.yaml and specify full path to resourcePool as specified in https://github.com/openshift/installer/blob/master/docs/user/vsphere/customization.md#cluster-scoped-properties

```console
# create install-config.yaml with vsphere configuration, set resourcePool to a valid resource pool with full path

# e.g. /Datacenter/host/Cluster/Resources/ourResourcePool

openshift-install create cluster

# wait 30 minutes or so

# vms will be created in /Datacenter/host/Cluster/Resources/ <- note they're in the Cluster's "root" resource pool.
```

Let me know if you need anything else. I've tried this a number of times, all with the same result. I tried doing an install from the manifest stage as well and was able to make that work but only by hand editing the manifests in openshift/99-*machineset.yaml files. I suspect that the resource pool is getting dropped somewhere between the install-config.yaml and the manifest stage.

for example:
```console
❯ grep resourcePool install-config.yaml 
    resourcePool: /Datacenter/host/funtime/Resources/city

❯ openshift-install create manifests
INFO Consuming Install Config from target directory 
INFO Manifests created in: manifests and openshift 

❯ ag resourcePool

openshift/99_openshift-cluster-api_worker-machineset-0.yaml
47:            resourcePool: /Datacenter/host/Cluster/Resources # where

openshift/99_openshift-cluster-api_master-machines-2.yaml
36:        resourcePool: /Datacenter/host/Cluster/Resources # did

openshift/99_openshift-cluster-api_master-machines-0.yaml
36:        resourcePool: /Datacenter/host/Cluster/Resources # it

openshift/99_openshift-cluster-api_master-machines-1.yaml
36:        resourcePool: /Datacenter/host/Cluster/Resources # go?
```

**Comment by staebler** [comment]
I suspect that you have a malformed install-config.yaml. Could you provide a more complete install-config.yaml with sensitive value redacted?

If you run `openshift-install create install-config`, the install-config.yaml in the installation directory will be what the installer is actually using, with any fields that you supplied that the installer does not recognize removed.

**Comment by nate-duke** [comment]
```yaml
apiVersion: v1
baseDomain: okd4.base-test.frustrated.admin
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.250.1.2
    cluster: Big Cluster
    datacenter: Main Datacenter
    defaultDatastore: OKD_DATASTORE
    ingressVIP: 10.138.5.153
    network: NETWORK
    password: password
    username: USERNAME
    vCenter: vsphere.frustrated.admin.
publish: External
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: |
  ssh-ed25519 deadbeef nate@frustrated.admin
```

How do we specify resource pool as specified [here](https://github.com/openshift/installer/blob/master/docs/user/vsphere/customization.md#cluster-scoped-properties)? The installer does *not* prompt for Resource Pool so I'd not really expect it to be in the generated configuration w/o it making some uninformed guess on its own.

**Comment by staebler** [comment]
The `resourcePool` field should be under `.platform.vsphere`.
```
apiVersion: v1
baseDomain: okd4.base-test.frustrated.admin
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.250.1.2
    cluster: Big Cluster
    datacenter: Main Datacenter
    defaultDatastore: OKD_DATASTORE
    ingressVIP: 10.250.1.3
    network: NETWORK
    password: password
    username: USERNAME
    vCenter: vsphere.frustrated.admin.
    resourcePool: /Datacenter/host/funtime/Resources/city
publish: External
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: |
  ssh-ed25519 deadbeef nate@frustrated.admin
```
