### ISSUE TITLE
Support For Variety Of Inexpensive EC2 Instance Types in AWS

### ISSUE THREAD

**Issue by ecda909** [openshift/installer#5592]
# Version

```console
$ openshift-install version
openshift-install 4.9.0-0.okd-2022-01-29-035536
built from commit 8d5b2831d3afa00a5a524283718c9577c957a49d
release image quay.io/openshift/okd@sha256:ce42e3e42c19b2d97f51221a65e1f97191b6f51f6e8552ba339dace501e29d1a
release architecture amd64
```

# Platform:
- AWS
- IPI

# What happened?
We provisioned nodes that were of type t3.medium (unsupported) and the cluster returned a response of 
```FATAL failed to fetch Metadata: failed to load asset "Install Config": [controlPlane.platform.aws.type: Invalid value: "t3.medium": instance type does not meet minimum resource requirements of 4 vCPUs, controlPlane.platform.aws.type: Invalid value: "t3.medium": instance type does not meet minimum resource requirements of 16384 MiB Memory, compute[0].platform.aws.type: Invalid value: "t3.medium": instance type does not meet minimum resource requirements of 8192 MiB Memory]```

# What you expected to happen?
We want to know if any work is in the pipeline for provisioning nodes that are less resources intensive such as the .medium series of the AWS instance types. If not, why so? The nodes may not meet the standards of the okd configuration required out-of-the-box, but I feel that there are members within the community who could greatly benefit from this type of modification, specifically developers looking to bootstrap their startups and subsequently have significantly less funds to operate with...

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
baseDomain:  <name>
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - us-east-1a
      - us-east-1b
      type: t3.medium
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - us-east-1a
      - us-east-1b
      type: t3.medium
  replicas: 1
metadata:
  creationTimestamp: null
  name: <name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
sshKey: |-

publish: External
pullSecret: "","email":""}}}'

```

Apply the config

``` 
./openshift-install create cluster --dir <dir_location> --log-level=info
```
# Anything else we need to know?

This is just a question and a proposal for future work, not a bug. I realize the documentation has reference to the restrictions on instance types, but just looking for more clarification on why things are the way they are :)
