### ISSUE TITLE
libvirt IPI in <= 4.9.z used to have a main.tf to customize the libvirt_network, how to do that with 4.10+ ?

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/installer#5724]
This file was present in all versions before 4.10.z:
https://github.com/openshift/installer/blob/release-4.9/data/data/libvirt/main.tf#L46-L71

It was useful to deploy on a NAT'ed network (libvirt).
Since main.tf is gone in 4.10.z+ how can we do something like this?

```resource "libvirt_network" "net" {
  name = var.cluster_id

  mode   = "nat"
  bridge = var.libvirt_network_if

  domain = var.cluster_domain

  addresses = var.machine_v4_cidrs

  dns {
    local_only = true
    forwarders { 
        address = "192.168.122.1"
        domain = "apps.${var.cluster_domain}" 
    }

    dynamic "hosts" {
      for_each = concat(
        data.libvirt_network_dns_host_template.bootstrap.*.rendered,
        data.libvirt_network_dns_host_template.bootstrap_int.*.rendered,
        data.libvirt_network_dns_host_template.masters.*.rendered,
        data.libvirt_network_dns_host_template.masters_int.*.rendered,
      )
      content {
        hostname = hosts.value.hostname
        ip       = hosts.value.ip
      }
    }
  }

  dnsmasq_options {
    dynamic "options" {
      for_each = concat(
        data.libvirt_network_dnsmasq_options_template.options.*.rendered,
      )
      content {
        option_name  = options.value.option_name
        option_value = options.value.option_value
      }
```

**Comment by ElCoyote27** [comment]
We used to do this because of https://github.com/openshift/installer/issues/1007

**Comment by ElCoyote27** [comment]
Got it working by adding this to my install-cfg:

```
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: net-ocp0
      dnsmasqOptions:  <=========
      - name: "address"  <=========
        value: "/.apps.ocp4d.openshift.lasthome.solace.krynn/192.168.246.51"  <=========

```
