### ISSUE TITLE
Feature/Version notification message

### ISSUE THREAD

**Issue by michaelalang** [openshift/installer#5971]
# Version

```
github master branch
```

# Platform:
all Platforms
* all installation types with customized parameters

# What happened?

The master branch README.md should provide a Notification for Users to understand that features included in more recent releases are not available in older versions (for example diskEncryptionSet)

# What you expected to happen?

a possible suggestion could be to include a Note between "Supported Platforms" and "Quick start" 

```
Be aware that features listed and or documented might not be available in the openshift-installer version your support vendor is shipping. 
You can switch the *branch* to see the documentation  and version features of your installer accordingly.
```

# How to reproduce it (as minimally and precisely as possible)?

* download openshift-installer for 4.10 
* grab any v4.11+ feature  
* try to utilize the feature 

```
cat install.yaml
[... output omitted ...]
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:  
      type: .....
      osDisk:
        diskSizeGB: 512
        diskType: ....
      diskEncryptionSet:
[... output omitted ...]
```
