### ISSUE TITLE
OC4.10 vsphere installer failed when Datacenter is created under folder

### ISSUE THREAD

**Issue by piyushkv1** [openshift/installer#5999]
# Version

```console
$ openshift-install version
openshift-install 4.10.16
built from commit a4b45c9948014b7631beec9a33382dcb6bced684
release image quay.io/openshift-release-dev/ocp-release@sha256:a546cd80eae8f94ea0779091e978a09ad47ea94f0769b153763881edb2f5056e
release architecture amd64
```

# Platform:

vsphere

IPI
# What happened?
Installer is not able to find vsphere cluster when Datacenter is created under folder. Here Datacenter is created under folder folder-os-test-dc.
[openshift_install.log](https://github.com/openshift/installer/files/8896692/openshift_install.log)

```
~# openshift-install create cluster --dir=/root/test
INFO Consuming Install Config from target directory
FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": platform.vsphere.network: Invalid value: "node-ls-1": could not find vSphere cluster at /os-test-dc/host/os-compute-cluster-1: cluster '/os-test-dc/host/os-compute-cluster-1' not found
```
Platform configuration:
```
platform:
  vsphere:
    apiVIP: 192.168.11.11
    cluster: os-compute-cluster-1
    datacenter: /folder-os-test-dc/os-test-dc
    defaultDatastore: sharedStorage
    ingressVIP: 192.168.11.12
    network: node-ls-1
    password: ***
    username: ***
    vcenter: ***
```

# What you expected to happen?

Installer works fine with Openshift 4.9 and lower version, this problem is seen only with Openshift 4.10 version.

# How to reproduce it (as minimally and precisely as possible)?

Create vSphere datacenter under folder and run command
```console
openshift-install create cluster --dir=/root/test/
```
