### ISSUE TITLE
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "Master Machines": failed to generate asset "Image": stable/x86_64: No azure build found

### ISSUE THREAD

**Issue by maxvandl** [openshift/installer#6191]
# Version

```console
$ openshift-install version
./openshift-install 4.11.0-0.okd-2022-07-29-154152
built from commit 37684309bcb598757c99d3ea9fbc0758343d64a5
release image quay.io/openshift/okd@sha256:a506d80873f7c51201c614be9c8defa6455f3b593faa54d11ded7b4d20c0fc4e
release architecture amd64
```

# Platform:

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

./openshift-install create cluster --log-level=debug

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

I try install old 4.11 on azure

```
apiVersion: v1
baseDomain: okd4.ru
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: okd4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: okd4-max
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: eastus
publish: External
pullSecret: ''
sshKey: |
```
