### ISSUE TITLE
Still waiting for the Kubernetes API debug error

### ISSUE THREAD

**Issue by norhther** [openshift/installer#6775]
# Version

```console
./openshift-install 4.11.0-0.okd-2023-01-14-152430
built from commit b1b244444835f9a3fd2c5e6717db9ba6d18607be
release image quay.io/openshift/okd@sha256:27c99f5b7734f773a7981b9e527417edcda0eee217117632198d64aa33e95c46
release architecture amd64

```

# Platform:
openstack

# What happened?

I'm trying to install openshift in a custom environment, with only one floating ip address. 
What I did was to create a machine in openstack and launch the installer from there.
However, I get the debug message repeatedly:

`DEBUG Still waiting for the Kubernetes API: Get "https://xxx:6443/version": dial tcp: lookup api.okd-cluster.okd.xxx on xxx: no such host`

# What you expected to happen?

Properly completion of the installer

# How to reproduce it (as minimally and precisely as possible)?

- Create a machine inside openstack
- Create a new network for the okd cluster
- Launch installer from the machine inside openstack with the following parameters

```
apiVersion: v1
baseDomain: okd.xxx
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    openstack:
      type: xxx
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    openstack:
      type: xxx
  replicas: 3
metadata:
  creationTimestamp: null
  name: okd-cluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.28.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    cloud: openstack
    defaultMachinePlatform:
      type: xxx
    externalDNS: null
    machinesSubnet: xxx
publish: External
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: |
  xxx
```
