### ISSUE TITLE
Allow external loadbalancer to be outside machine cidr range.

### ISSUE THREAD

**Issue by ppeereb1** [openshift/installer#7476]
# Version

```console
$ openshift-install version
openshift-install version
openshift-install 4.13.9
built from commit 9e2176e786c194d0f8c85c33f799236655cb7b4d
release image quay.io/openshift-release-dev/ocp-release@sha256:a266d3d65c433b460cdef7ab5d6531580f5391adbe85d9c475208a56452e4c0b
release architecture amd64
```

# Platform:
baremetal agent based installer

# What happened?

Now that external loadbalancer is in code (https://github.com/openshift/installer/commit/625932f5c345e08f49581973bb88acb25d0bca10 )  as tech preview I was testing it a bit. But i'm unable to bootstrap a cluster because it expects that our external loadbalancer is within the machine cidr range, which in our case is not:

``` 
        10.123.127.0/24

┌───────────┐     ┌──────────┐
│           │     │          │
│           │     │          │
│  Lb1      │     │  Lb2     │
│           │     │          │
└─────────┬─┘     └─┬────────┘
          │         │ VIPS:
          └────┬────┘ 10.123.127.10 (API)
               │      10.123.127.11 (ingress)
               │
               │
               │
               │
      ┌────────┴────────┐
      │                 │
┌─────┴─────┐     ┌─────┴─────┐
│           │     │           │
│ Worker1   │     │ Worker2   │
│ (ingress) │     │ (ingress) │
└───────────┘     └───────────┘
   10.124.0.5       10.124.0.6

            10.124.0.0/24
```

My install-config.yaml:
```
apiVersion: v1
baseDomain: example.com
metadata:
  name: dev
networking:
  machineNetwork:
    - cidr: 10.124.32.0/19
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 25
  serviceNetwork:
    - 172.30.0.0/16
  networkType: OVNKubernetes
compute:
- name: worker
  hyperthreading: Disabled
  replicas: 9
controlPlane:
  name: master
  hyperthreading: Enabled
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    loadBalancer:
      type: UserManaged
    apiVIPs:
    - 10.123.127.10
    ingressVIPs:
    - 10.123.127.11
featureSet: TechPreviewNoUpgrade
```

openshift-install agent create cluster-manifests  --dir /tmp
```
platform.baremetal.apiVIPs: Invalid value: "10.123.127.10": IP expected to be in one of the machine networks: 10.124.32.0/19, platform.baremetal.ingressVIPs: Invalid value: "10.123.127.11": IP expected to be in one of the machine networks: 10.124.32.0/19
```
# What you expected to happen?
When defining your own loadbalancer it should also be possible to use them in an other subnet than the machinenetwork.
