### ISSUE TITLE
RHOS 4.14 on vsphere environment

### ISSUE THREAD

**Issue by Nzaca** [openshift/installer#7690]
Hi, 
I am trying to create OpehShift cluster for test purpose on vsphere , In my lab network there is no DHCP server so in install-config.yaml file I try to setup manual IP address for bootstrap , master and worker node.

# Version

```console
$ openshift-install version 
4.14
```

# Platform:
vsphere 7

/install-config.yaml :
```
additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: vsphere.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: rhoc
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    hosts:
    - role: bootstrap
      networkDevice:
        ipAddrs:
        - 192.168.1.10/24
        gateway: 192.168.1.1
        nameservers:
        - 192.168.1.100
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 192.168.1.11/24
        gateway: 192.168.1.1
        nameservers:
        - 192.168.1.100
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 192.168.1.12/24
        gateway: 192.168.1.1
        nameservers:
        - 192.168.1.100
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 192.168.1.13/24
        gateway: 192.168.1.1
        nameservers:
        - 192.168.1.100
    - role: compute
      networkDevice:
        ipAddrs:
        - 192.168.1.14/24
        gateway: 192.168.1.1
        nameservers:
        - 192.168.1.100
    - role: compute
      networkDevice:
        ipAddrs:
        - 192.168.1.15/24
        gateway: 192.168.1.1
        nameservers:
        - 192.168.1.100
    apiVIPs:
    - 192.168.1.20
    failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: vcsa.vsphere.local
      topology:
        computeCluster: /DClab/host/lab
        datacenter: DClab
        datastore: /DClab/datastore/DCLab
        networks:
        - "lab_net"
        resourcePool: /DClab/host/lab/Resources
      zone: generated-zone
    ingressVIPs:
    - 192.168.1.21
    vcenters:
    - datacenters:
      - DClab
      password: 
      port: 443
      server: vcsa.vsphere.local
      user: administrator@vsphere.local
```

# What happened?
Bootstrap machine doesn't get ip address 

# What you expected to happen?

Enter text here.
