### ISSUE TITLE
proxy:  failed to unmarshal install-config.yaml

### ISSUE THREAD

**Issue by n00bsi** [openshift/installer#8305]
# Version

```
built from commit f4f5d0ee0f7591fd9ddf03ac337c804608102919
release image quay.io/openshift-release-dev/ocp-release@sha256:5c82cea5931996af509231c7a5a1611bcfd927dca4e362e6443d1f8a77a517c2
release architecture amd64

```

# Platform: vSphere

# What happened?

Installer complains that the install-config.yaml is not valid

# What you expected to happen?

that the installer accept the yaml

# How to reproduce it (as minimally and precisely as possible)?

install-config.yaml

```
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  httpProxy: http://username:password@proxy.ourdomain.tld:3128
  httpsProxy: http://username:password@proxy.ourdomain.tld:3128
  noProxy: ourdomain.tld
  readinessEndpoints:
  - http://www.google.com 
  - https://www.google.com
  trustedCA:
    name: user-ca-bundle 

```

```
$ ./openshift-install create cluster
WARNING failed to parse first occurrence of unknown field: failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field "spec" 
INFO Attempting to unmarshal while ignoring unknown keys because strict unmarshaling failed 
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: failed to upconvert install config: apiVersion: Invalid value: "config.openshift.io/v1": cannot upconvert from version config.openshift.io/v1 

```

how to fix this install-config.yaml

used this https://docs.openshift.com/container-platform/4.15/networking/enable-cluster-wide-proxy.html
as template

When using this:

```
apiVersion: v1
baseDomain: ourdomain.tld
metadata:
  name: cluster
proxy:
  httpsProxy: http://user:password@proxy.ourdomain.tld:3128/
  httpProxy: http://user:password@proxy.ourdomain.tld:3128/
  noProxy: .ourdomain.tld,10.199.0.0/20,10.199.16.0/24
platform: vsphere
pullSecret: '{"auths":... '

```

got this error:

`ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field InstallConfig.platform of type types.Platform 
`
