### ISSUE TITLE
OpenShift IPI Installation on VSphere with static IPs does not set the correct Hostnames on Nodes

### ISSUE THREAD

**Issue by Mikesch-the-Cat** [openshift/installer#9660]
Dear all,

i have created a install-config.yaml file with this parameters:

```
apiVersion: v1
baseDomain: test.dev
metadata:
  name: ocp4
compute:
- architecture: amd64
  name: worker
  hyperthreading: Enabled
  replicas: 3
  platform:
    vsphere:
      cpus: 2
      coresPerSocket: 1
      memoryMB: 8192
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
platform:
  vsphere:
    loadBalancer:
      type: UserManaged
    failureDomains:
    - name: "dc-east-1"
      region: "my-datacenter"
      server: vsphere.example.com
      topology:
        computeCluster: /Datacenter/host/DRS-FFM
        datacenter: Datacenter
        datastore: /Datacenter/datastore/DS_Test
        folder: "/Datacenter/vm/Testing/OpenShift"
        networks:
        - DMZ10332016
        resourcePool: /Datacenter/host/DRS-FFM/Resources
      zone: DRS-FFM
    hosts:
    - role: bootstrap
      # hostname: ocp4-bootstrap.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.18/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    - role: control-plane
      # hostname: controlnode1.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.22/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    - role: control-plane
      # hostname: controlnode2.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.23/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    - role: control-plane
      # hostname: controlnode3.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.24/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    - role: compute
      # hostname: computenode1.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.25/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    - role: compute
      # hostname: computenode2.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.26/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    - role: compute
      # hostname: computenode3.test.dev
      networkDevice:
        ipAddrs:
        - 10.33.2.27/28
        gateway: 10.33.2.17
        nameservers:
        - 10.43.0.50
        - 10.43.0.51
    vcenters:
    - datacenters:
      - Datacenter
      user: administrator@vsphere.local
      password: '*******'
      server: vsphere.example.com
      port: 443
    apiVIP: 10.33.2.28
    ingressVIP: 10.33.2.29
    defaultDatastore: /Datacenter/datastore/DS_Test
    network: DMZ10332016
fips: false
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.33.2.16/28
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{ ... }}}'
sshKey:  |
  ssh-rsa AAAAB3NzaC1...
```

On the Bootstrap Node and Vsphere Server the DNS Reverse Lookup works as expected

```
$ nslookup 10.33.2.22
22.2.33.10.in-addr.arpa name = controlnode1.ocp4.test.dev.
```

```
$ nslookup 10.33.2.23
23.2.33.10.in-addr.arpa name = controlnode2.ocp4.test.dev.
```

```
$ nslookup 10.33.2.24
24.2.33.10.in-addr.arpa name = controlnode3.ocp4.test.dev.
```

```
$ nslookup 10.33.2.25
25.2.33.10.in-addr.arpa name = computenode1.ocp4.test.dev.
```

```
$ nslookup 10.33.2.26
26.2.33.10.in-addr.arpa name = computenode2.ocp4.test.dev.
```

```
$ nslookup 10.33.2.27
27.2.33.10.in-addr.arpa name = computenode3.ocp4.test.dev.
```

```
$ nslookup 10.33.2.28
28.2.33.10.in-addr.arpa name = api-int.ocp4.test.dev.
28.2.33.10.in-addr.arpa name = api.ocp4.test.dev.
```

```
$ nslookup 10.33.2.29
29.2.33.10.in-addr.arpa name = *.apps.ocp4.test.dev.
```

The Installation creates all Control-Plane & Compute Nodes, but with the false names, it does not set the hostnames from the DNS Reverse Lookups.

```
10.33.2.22 = ocp4-wxwpn-master-0
10.33.2.23 = ocp4-wxwpn-master-1
10.33.2.24 = ocp4-wxwpn-master-2
10.33.2.25 = ocp4-wxwpn-worker-0
10.33.2.26 = ocp4-wxwpn-worker-1
10.33.2.27 = ocp4-wxwpn-worker-2
```

We don't use a DHCP Server for this Environment, so we have created static IP "A" Records with Reverse Lookup Entries.

Here are an example from a worker node after the Cluster is UP&Running, but with false Hostnames:

```
[core@ocp4-wxwpn-worker-0 ~]$ nslookup 10.33.2.22
;; Got recursion not available from 10.33.2.25, trying next server
22.2.33.10.in-addr.arpa name = col02db01os01.ocp4.test.dev.
```

How can i solve this issue?

Very thanks for your Help ad best regards,
Mikesch
